### ISSUE TITLE
HP with pseudo webservice

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/manufacturersimports#1]
Try to use hp webservice isee.

So convert https://github.com/iutrs/hpisee (python) in the php plugin

**Comment by moobyfr** [comment]
hpisee works only with HPE  (so servers), but no more for computers. Something else should be planned.

**Comment by tsmr** [comment]
We found another web service : Can you try with this address ?
productNo + serialNo
https://hpscm-pro.glb.itcs.hp.com/mobileweb/hpsupport.asmx/GetEntitlementDetails?productNo=491315-421&serialNo=CZC948039R&countryCode=null

**Comment by agazo** [comment]
I have submitted a PR #30 with support for HPE products based on the web service mentioned on comment from tsmr on 4th Nov.
