### ISSUE TITLE
The action you have requested is not allowed

### ISSUE THREAD

**Issue by Edzilla2000** [InfotelGLPI/manufacturersimports#101]
* Version of the plugin : 2.3.1

* Version of your GLPI : 9.5.6

* Steps to reproduce (which actions have you made) :
Try to import the warranty of a computer

* Expected result :
GLPI contacts Dell and imports the computer

* Actual result :
"The action you have requested is not allowed" message

* URL of the page :
https://glpi/plugins/manufacturersimports/ajax/massiveaction.php

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/5339038/146004779-4b1ec294-a5cb-4c34-9590-3fc96d975e3e.png)

This is my Dell configuration but I get the same result on Lenovo import: 
![image](https://user-images.githubusercontent.com/5339038/146004835-493c9760-51fb-4b40-a61e-4742f810f6e0.png)

I'm doing this with the GLPI account which is superadmin:
![image](https://user-images.githubusercontent.com/5339038/146004992-906fb0b6-bc31-42c3-af17-1115b65e29b8.png)

**Comment by Edzilla2000** [comment]
It seems the issue is the same as #100 and the fix is here: https://github.com/InfotelGLPI/manufacturersimports/commit/5b2911e671e69b174f9181d7952ac766a6b9d16e
Shouldn't there be a new release if the current version in the releases can't work?

**Comment by alifro81** [comment]
Hello,

I also have the same problem, and when I modify the command line, I get the result:
![image](https://user-images.githubusercontent.com/71875810/147229159-ba372a93-ea83-4e9d-a6ce-53664b93b156.png)

Could you find a solution?
Sincerely

**Comment by tsmr** [comment]
> Hello,
> 
> I also have the same problem, and when I modify the command line, I get the result: ![image](https://user-images.githubusercontent.com/71875810/147229159-ba372a93-ea83-4e9d-a6ce-53664b93b156.png)
> 
> Could you find a solution? Sincerely

copy plugins/manufacturersimports/ajax/massiveaction.php to plugins/manufacturersimports/front/massiveaction.php

**Comment by alifro81** [comment]
now it works :)
thank you for the correction ^^
![image](https://user-images.githubusercontent.com/71875810/147240097-8cec8a0b-48b8-4b19-b050-8d56c8629d39.png)

Cdt

**Comment by Arno38** [comment]
Thanks for this !!

**Comment by tsmr** [comment]
Old issue, i close
