### ISSUE TITLE
Toshiba is broken

### ISSUE THREAD

**Issue by TheRoby** [InfotelGLPI/manufacturersimports#105]
* Version of the plugin : 
2.3.2

* Version of your GLPI : 
9.5.7

* Steps to reproduce (which actions have you made) :
Add a toshiba computer and a rules

* Expected result :
Add the warranty infos

* Actual result :
error
------------
Hello,

I use your plugin for Dell and Lenovo and it's work fine !
But i have now some Toshiba computer. When i add the rules, the default URL is :
http://aps2.toshiba-tro.de/unit-details-php/unitdetails.aspx?
but, toshiba-tro.de seems to be down ...
if found a new url :
https://aps2.support.emea.dynabook.com/unitdetails/unitdetails.aspx?
but, i think, there are some changes on Toshiba ... so the import failed ...

Thank you :)

**Comment by tsmr** [comment]
Old issue, i close
