### ISSUE TITLE
GLPI 10.0.0 Rc3 Dell import not working 

### ISSUE THREAD

**Issue by johndu30160** [InfotelGLPI/manufacturersimports#107]
* Version of the plugin : 3.0.0-rc1

* Version of your GLPI : 10.0.0-rc3

* Steps to reproduce (which actions have you made) : make a warranty import

* Expected result :

* Actual result : Import KO

* URL of the page : http://srv-glpi/marketplace/manufacturersimports/front/massiveaction.php

Hello,

I have a problem with dell warranty import.

The result is KO.

I trying different warranty url, but not working.

With soapui all is fine.

Can you help me ?

**Comment by tsmr** [comment]
Can you try with master version ? 
https://github.com/InfotelGLPI/manufacturersimports/archive/refs/heads/master.zip

**Comment by johndu30160** [comment]
It's not working.
the link for the dell garantuee is : https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-components

**Comment by tsmr** [comment]
Sorry but it's ok for me with master version : 
URL : https://www.dell.com/support/home/product-support/servicetag/
API : https://apigtwb2c.us.dell.com/auth/oauth/v2/token
Address API : https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=

**Comment by johndu30160** [comment]
For installation of the master version,
maje a copy of the file in the marcketplace directori is ok ? Or is another manipulation ?
Thanks for your help.

**Comment by johndu30160** [comment]
Hey man, i'm retryting a copy of the master file.
I execute the commande for the migration of the column.
I've enterred your url's and it's working.
thanks very much.
