### ISSUE TITLE
Pas d'import de la date de début de garantie Dell

### ISSUE THREAD

**Issue by asvm30** [InfotelGLPI/manufacturersimports#109]
Version of the plugin : 3.0.0

Version of your GLPI : 10.0.0

Version MariaDB : 10.6.7

* Expected result :Les informations de garantie sont importées dans GLPI pour Dell

* Actual result : Seules les information sur la garantie et la durée de garantie sont importées, pas d'importation de la date d'achat et de la date de début de garantie
/var/www/html/glpi/files/_log/sql-errors.log

*** MySQL query error:
  SQL: UPDATE `glpi_infocoms` SET `buy_date` = '2021-01-15T00:00:00+00:00' WHERE `id` = '15091'
  Error: Incorrect date value: '2021-01-15T00:00:00+00:00' for column `glpi`.`glpi_infocoms`.`buy_date` at row 1
  
  *** MySQL query error:
  SQL: UPDATE `glpi_infocoms` SET `warranty_date` = '2022-01-16T00:00:00+00:00' WHERE `id` = '15091'
  Error: Incorrect date value: '2022-01-16T00:00:00+00:00' for column `glpi`.`glpi_infocoms`.`warranty_date` at row 1

* URL of the page :

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/104882656/166624117-776a5da5-c9cb-4b26-b542-8f8aefb456cb.png)

**Comment by Re1Ser** [comment]
Bonjour !

Comment as-tu fait pour résoudre ce problème ? 

Merci d'avance !

**Comment by asvm30** [comment]
Bonjour

Le problème n'a jamais été résolu, je ne suis pas à l'origine de la fermeture du ticket.

Cordialement,

**Comment by BLINGjj** [comment]
Bonjour,

Quel est votre problème ?

Sur le plugins manufacturer import?

Envoyé avec la messagerie sécurisée [Proton Mail](https://proton.me/).

------- Original Message -------
