### ISSUE TITLE
LENOVO Import

### ISSUE THREAD

**Issue by pablitobin** [InfotelGLPI/manufacturersimports#110]
Team, 
I am using GLPI 9.4.5.
Plugin v. 2.2.2

Lenovo import does not work. I think that they are using a new API. Is this working?

**Comment by BLINGjj** [comment]
Hi pablitobi, 

Do u know where i can ask for the api key on lenovo?

**Comment by pablitobin** [comment]
It was a terrible mess. Let me find the contact.
Do you know how to fix lenovo import? It does not work.

**Comment by BLINGjj** [comment]
Can u show me the configuration of you're plugin ? ( hide the api key )

**Comment by pablitobin** [comment]
> Hi pablitobi,
> 
> Do u know where i can ask for the api key on lenovo?

gmalayao@lenovo.com

**Comment by BLINGjj** [comment]
> 

Thx , but i don't know how to send u  aprivate message , i'm new on github

**Comment by pablitobin** [comment]
This is my current setting, someone knows why it does not work?
![image](https://user-images.githubusercontent.com/40396227/170329496-08bacd64-e5f3-42c2-838a-71ca4f163f2c.png)

**Comment by BLINGjj** [comment]
Hello pablitobin , 

I think you need to fill Default supplier attached , the plugins need to know which supplier to work :)

**Comment by tsmr** [comment]
Try with 3.0.6 version of plugin
