### ISSUE TITLE
SQL Date format error

### ISSUE THREAD

**Issue by grigribou** [InfotelGLPI/manufacturersimports#113]
* Version of the plugin : 
3.0.1

* Version of your GLPI : 
10.0.0

* Steps to reproduce (which actions have you made) :
Import DELL warranty

* Expected result :
Purchase and warranty date to be imported

* Actual result :
No date imported, only waranty duration and comment are imported

in log I can see corresponding SQL error:

[2022-06-10 12:25:39] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/src/DBmysql.php line 368
  *** MySQL query error:
  SQL: UPDATE `glpi_infocoms` SET `buy_date` = '2014-04-24T00:00:00+00:00' WHERE `id` = '14424'
  Error: Incorrect date value: '2014-04-24T00:00:00+00:00' for column `glpi_prod`.`glpi_infocoms`.`buy_date` at row 1
  Backtrace :
  src/DBmysql.php:1429
  src/CommonDBTM.php:638                             DBmysql->update()
  src/CommonDBTM.php:1627                            CommonDBTM->updateInDB()
  ...nufacturersimports/inc/postimport.class.php:699 CommonDBTM->update()
  ...nufacturersimports/inc/postimport.class.php:601 PluginManufacturersimportsPostImport::saveInfocoms()
  ...nufacturersimports/inc/postimport.class.php:462 PluginManufacturersimportsPostImport::saveImport()
  ...nufacturersimports/inc/postimport.class.php:233 PluginManufacturersimportsPostImport::seePostImport()

running SQL: _UPDATE `glpi_infocoms` SET `buy_date` = '2014-04-24T00:00:00' WHERE `id` = '14424'_ is OK, but query generated by pluggin is with a different date format : _UPDATE `glpi_infocoms` SET `buy_date` = '2014-04-24T00:00:00**+00:00**' WHERE `id` = '14424'_

I have no idea if it's related to PHP (PHP 8.1.5) version or mariadb version.

**Comment by tsmr** [comment]
If you can, you can try to replace each format('c'); by format('Y-m-d H:i:s'); into inc/dell.class.php ?
