### ISSUE TITLE
Dell Warranty Import fails

### ISSUE THREAD

**Issue by supertramp4** [InfotelGLPI/manufacturersimports#114]
HI
* Version of the plugin : 3.0.1
* Version of your GLPI : 10.0.1
* Steps to reproduce (which actions have you made) :
Tools -> Supplier Imports -> Select Computers/Dell/Devices not imported
Select the Computer -> Import -> Post

* Expected result :
1) the Link to the Manufactruers website works correctly
2) the warranty information to be imported

* Actual result :
GLPI displays an error message "Problem during the importation"

* URL of the page :
http://<server>/glpi/plugins/manufacturersimports/front/import.php

* Screenshot of the problem (if pertinent) :

* Errors
The glpi\files\_log\php-errors.log contains the following error as a result of the attempted import 
`
[2022-06-14 09:51:15] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "supplier_key" in C:\Apache24\htdocs\glpi\plugins\manufacturersimports\inc\config.class.php at line 661
  Backtrace :
  ...s\manufacturersimports\front\config.form.php:72 PluginManufacturersimportsConfig::retrieveOneWarranty()
  
[2022-06-14 09:51:15] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "PluginManufacturersimports" not found in C:\Apache24\htdocs\glpi\plugins\manufacturersimports\inc\config.class.php at line 680
  Backtrace :
  ...s\manufacturersimports\front\config.form.php:72 PluginManufacturersimportsConfig::retrieveOneWarranty()
`
Thanks
Chris

**Comment by supertramp4** [comment]
Hi, can anyone give any guidance on this problem please ?

**Comment by bacus99** [comment]
Have you try to uninstall it then reimport from the marketplace?

**Comment by bacus99** [comment]
I had this kind of error when I upgrade (but overwrite the files).  Try to delete the folder, copy back the new files

**Comment by supertramp4** [comment]
Hi,
1) this is not an upgrade, this is a brand new fresh install of glpi 10.0.1, and your plugin.
2) today when I reinstalled, I did delete the folder under /plugins then extracted the folder from the bz2 zip
3) after installing the plugin, I just created 1 entry with the predefined "Dell" information.

I'm not very php literate but happy to help with debugging in any way I can to help you.
Thanks




Sent from my Galaxy



-------- Original message --------
From: Christian Bernard ***@***.***>
Date: 21/06/2022 16:14 (GMT+00:00)
To: InfotelGLPI/manufacturersimports ***@***.***>
Cc: Chris Bridges ***@***.***>, Author ***@***.***>
Subject: Re: [InfotelGLPI/manufacturersimports] Dell Warranty Import fails (Issue #114)



I had this kind of error when I upgrade (but overwrite the files). Try to delete the folder, copy back the new files

—
Reply to this email directly, view it on GitHub<https://eu-west-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL0luZm90ZWxHTFBJL21hbnVmYWN0dXJlcnNpbXBvcnRzL2lzc3Vlcy8xMTQjaXNzdWVjb21tZW50LTExNjE4OTk5Nzc=&i=NWVjMzg3N2VkMTQ0NGExNmIxYTU4MWUy&t=a2dneis1WWZvdTlzTzVKeE9sVGl5Y2Mvbjd0dmZrdkcwdHFIS2lqYWlXST0=&h=ec85f793666c442fbbf11ee1361d4253>, or unsubscribe<https://eu-west-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BTEY3TkxERlVZV0hFNTI1QVlOWTZRRFZRSEw0NUFOQ05GU001WVhFNlhUUQ==&i=NWVjMzg3N2VkMTQ0NGExNmIxYTU4MWUy&t=bUtUNkdIWllPby9yUm92V3RRSC9rdVY2eE00M0hLRlR0a1QyQTVhemJaUT0=&h=ec85f793666c442fbbf11ee1361d4253>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


Chris Bridges
Deputy Head of IT

E: ***@***.***
T: +44 (0)1983 216631
M: +44 (0)7776 234533
Rheinmetall Electronics UK (formerly RFEL)

[rheinmetall.com logo]<https://www.rheinmetall.com>
***@***.***<http://>

Rheinmetall Electronics UK Ltd., Unit B, The Apex, St Cross Business Park, Newport, Isle of Wight, PO30 5XW, United Kingdom (Company No: 2389307) T: +44(0)1983 216600
This email may contain confidential information. If you are not the intended addressee, or if the information provided in this email (including any attachments) is evidently not destined for you, kindly inform us promptly and delete the message received in error (including any attachments) by erasing it from all your computers and other storage devices or media and destroying any hard copies thereof. Any unauthorized processing, forwarding, disclosure, distribution, divulgation, storage, printout or other use of this message or its attachment is prohibited. If your system is infected or otherwise bugged by any virus that is carried by this email, we disclaim any liability whatsoever for the ensuing loss or damage unless caused by our intention or gross negligence.
The views of the author may not necessarily constitute the views of Rheinmetall Electronics UK Ltd.

**Comment by bacus99** [comment]
Mine on linux

Have you configure your dell account properly?

**Comment by supertramp4** [comment]
Hi, Yes, i have my API Keys, and i just get the error "Connection failed/data download from manufacturer web site".
There are no log file entries 
I have tried the API Addresses with or without the trailing slash
https://xxxxx.us.dell.com/auth/oauth/v2/token/
https://xxxxx.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements/
I have just upgraded to GLPI 10.0.2, but no change
If i try the connection using the powershell script provided at https://www.hull1.com/scriptit/2020/08/28/dell-api-warranty-lookup.html then the details are retrieved correctly
PS D:\cb> .\dell_api.ps1
Enter ServiceTag [] : xxxxxxx
Service Tag   : xxxxxxx
Model         : XPS 15 9570
Type          : laptop
Ship Date     : 10-17-18
Warranty Exp. : 10-18-22

**Comment by cmoreno038** [comment]
I have same error but this log

[2022-08-18 15:50:27] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function _s() in /var/www/html/glpi/marketplace/manufacturersimports/inc/preimport.class.php at line 983
  Backtrace :
  ...anufacturersimports/inc/preimport.class.php:584 PluginManufacturersimportsPreImport::printPager()
  ...tplace/manufacturersimports/front/import.php:43 PluginManufacturersimportsPreImport::seePreImport()

GLPI Version: 10.0.2
Suppliers imports Plugin Version: 3.0.1

Regards

**Comment by Wolvverine** [comment]
```
Correct configuration:
Manufacturer web address: https://www.dell.com/support/home/product-support/servicetag/ 
Access token API address: https://apigtwb2c.us.dell.com/auth/oauth/v2/token
Warranty API address: https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=
```

**Comment by tsmr** [comment]
Old issue, i close
