### ISSUE TITLE
Warranty info page not displaying Warranty Start date and end date

### ISSUE THREAD

**Issue by tcapacci** [InfotelGLPI/manufacturersimports#115]
Hi
------------
* Version of the plugin : 
	manufacturersimports Name: Suppliers imports              Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
* Version of your GLPI : 
GLPI 10.0.2

* Steps to reproduce (which actions have you made) :
Import Computers from the Suppliers plugin

* Expected result :
Import is OK, Warranty info are correctly retrieved

* Actual result :
No Start date of Warranty on the GLPI Warranty info page
Valid to...is empty

* Screenshot of the problem (if pertinent) :
<img width="2232" alt="Greenshot 2022-07-19 11 33 55" src="https://user-images.githubusercontent.com/13747663/179718616-c9d335f2-993c-452d-b96e-2f36516ae682.png">

**Comment by HaZet1968** [comment]
Same here. Manual installation

**Comment by grigribou** [comment]
Same as #113

**Comment by TheRoby** [comment]
I have change this :
https://github.com/InfotelGLPI/manufacturersimports/pull/117

now it's ok for me :)

**Comment by tcapacci** [comment]
works for me too :)

**Comment by tsmr** [comment]
Old issue, i close
