### ISSUE TITLE
HP API not working

### ISSUE THREAD

**Issue by maxplettenberg** [InfotelGLPI/manufacturersimports#119]
@tsmr thanks for updating the file. seems that the right uri is working now. But I get an import failed message if I try to import the warranty data of HP and no data is imported. 

Additionally the API works well with printer warranty as well and the field "WarProduct" is a reference for the booked service/warranty product with the internal HP product no for e.g. U4414E - 3y NextBusinessDay this information would be great for the field "Warranty information" 
![grafik](https://user-images.githubusercontent.com/50808363/200319178-351f52f7-bd22-49ab-a318-9c50b4304a1d.png)

_Originally posted by @maxplettenberg in https://github.com/InfotelGLPI/manufacturersimports/issues/118#issuecomment-1305600080_

**Comment by tsmr** [comment]
Could you give me serial number for test ?

**Comment by maxplettenberg** [comment]
yes try:
https://warrantyapiproxy.azurewebsites.net/api/HP?serial=5CG12747TG

**Comment by fred7253** [comment]
Bonjour,

idem pour moi, impossible de récupérer les infos de garantie de mon parc HP via le plugin Import Fabricants v3.0.4
pour test: https://warrantyapiproxy.azurewebsites.net/api/HP?serial=5CD2077GD3

**Comment by tsmr** [comment]
Can you try https://github.com/InfotelGLPI/manufacturersimports/commit/b733911c8dd6e7d29de13c4b66b8867a979f3ca2 ?

**Comment by tsmr** [comment]
New release

**Comment by maxplettenberg** [comment]
Kudos! Works fine! Thanks for the quick response!
