### ISSUE TITLE
Fujitsu import 

### ISSUE THREAD

**Issue by anthonymontebrun** [InfotelGLPI/manufacturersimports#120]
Hello,

Automatic import for Fujitsu doesn't seem to work anymore, the default url doesn't seem to work anymore.

Sincerely,

------------
* Version of the plugin : 3.0.5

* Version of your GLPI : 10.0.5

* Steps to reproduce (which actions have you made) : Use preconfiguration for Fujitsu

* Expected result : Get information

* Actual result : Failed

* URL of the page : https://support.ts.fujitsu.com/ProductCheck/Default.aspx?Lng=en&GotoDiv=Warranty/WarrantyStatus&DivID=indexwarranty&GotoUrl=IndexWarranty&RegionID=1&Token=$%7B$i$M$f$u&Ident=

* Screenshot of the problem (if pertinent) :

**Comment by tsmr** [comment]
And with this URL : http://support.ts.fujitsu.com/Warranty/WarrantyStatus.asp?lng=com&IDNR in setup ?

**Comment by anthonymontebrun** [comment]
I have the same problem.

**Comment by anthonymontebrun** [comment]
Hello,

Do you have another proposal ?

Sincerely,

**Comment by Stephane41000** [comment]
The new URL is [https://support.ts.fujitsu.com/IndexWarranty.asp?lng=COM](url)

**Comment by anthonymontebrun** [comment]
I tried several URLs without success...

**Comment by tsmr** [comment]
Try with 3.0.6 version of plugin
