### ISSUE TITLE
LENOVO Problem during the importation but warranty is retrieved by URL

### ISSUE THREAD

**Issue by TylerVD** [InfotelGLPI/manufacturersimports#125]
* Version of the plugin : 3.0.5

* Version of your GLPI : 10.0.5

* Steps to reproduce (which actions have you made) :
   Import warranty with:
    <img width="290" alt="image" src="https://user-images.githubusercontent.com/82641169/215064417-dbf1fa9b-d0d3-4eb8-9001-68698fec7eac.png">
   Check a computer then submit: 
    <img width="334" alt="image" src="https://user-images.githubusercontent.com/82641169/215064522-c3700c7e-472d-46d0-abe3-70e89bd4d793.png">
   Show Problem during the importation but warranty is retrieved manually by URL manufacturer provided on the page https://pcsupport.lenovo.com/products/XXXXXXX/warranty

* Expected result :
Get the infos from Lenovo and set status to "Already imported"

* Actual result :
Error and status set to "Problem during the importation" and the error count of not retrieved computers is 

* URL of the page :
https://support-it.ratpdev.com/marketplace/manufacturersimports/front/import.php

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/82641169/215063474-e3c75bd6-e6c7-46b4-9976-15c2ad6f85e6.png)
<img width="935" alt="image" src="https://user-images.githubusercontent.com/82641169/215063905-c898312f-dca7-4af7-a646-e9432e256ec2.png">

**Comment by liedekef** [comment]
You might want to check my PR: https://github.com/InfotelGLPI/manufacturersimports/pull/127

**Comment by TylerVD** [comment]
Hello,
Still KO :(

<img width="893" alt="image" src="https://user-images.githubusercontent.com/82641169/218751059-c61ab1eb-9d75-461e-a1e6-4bc3db0662d5.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/82641169/218751396-9f9e55e6-7bc7-4cf1-b9c1-11baf355ee09.png">

**Comment by liedekef** [comment]
Did you first "reset the import"? Otherwise nothing happens during import. I tried it here: works fine ...

**Comment by liedekef** [comment]
Also: no supplier attached? I think you need to attach a supplier too ...

**Comment by TylerVD** [comment]
You are the best !
Working with a reset before.
Thx 👍

**Comment by TheRoby** [comment]
> Also: no supplier attached? I think you need to attach a supplier too ...

Hi, i don't attach a supplier and the import work :)

But, for a computer who has : 

![image](https://user-images.githubusercontent.com/6053818/218775425-a07f7ea7-eaf7-481d-a3dd-6e51a53dc382.png)

the import his :

![image](https://user-images.githubusercontent.com/6053818/218775515-cc335bed-4739-472e-bf4f-74c14d059495.png)

so with 12 month warranty the end date is ok, but i think indicate 36 month is better no ?

Thank you :)

**Comment by liedekef** [comment]
Well, I checked my code and it is not 100% in info, I'll rework it a bit. Also, if you can send me your serial by email, I can also include that in my tests then :-)

**Comment by liedekef** [comment]
I updtaed the code, can you check the new version of the pull request? This is the change compared to the original:
https://github.com/InfotelGLPI/manufacturersimports/pull/127/files

**Comment by TheRoby** [comment]
It's ok for me : 
Fournisseur: Date d'achat: 21-06-2022->15-12-2022
Date de début de garantie: 14-12-2025->15-12-2022
Durée de garantie: 12->36

Thank you :)
