### ISSUE TITLE
Import HP KO - Website closed

### ISSUE THREAD

**Issue by tonydecastro** [InfotelGLPI/manufacturersimports#126]
Bonjour,

Le site https://warrantyapiproxy.azurewebsites.net/api/HP?serial=
semble down depuis plusieurs jours, la webapp est stoppé.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/101981647/216078525-694fad8e-4e37-4b75-b904-9cd7b13db4a1.png">

Du coup retour sur le site  https://support.hp.com/fr-fr/check-warranty à la main.
Je fouille encore voir si je trouve plus d'info.

**Comment by pierrebaridon** [comment]
Bonjour,

HP ne propose plus d'API publique.
L'accès à une nouvelle API est maintenant proposée par HP à la demande des clients (comme DELL) et avec une authentification.
Est-ce qu'il serait possible de faire évoluer le plugin dans ce sens ?

cordialement,

**Comment by tsmr** [comment]
Try with 3.0.6 version of plugin
