### ISSUE TITLE
Warranty start date error with Dell API

### ISSUE THREAD

**Issue by cyrakuse** [InfotelGLPI/manufacturersimports#128]
Hello,

I use the last version of the plugin and i have a problem with Dell warranty import.
The buy date is correct.
The warranty  end date is correct.
But the warranty start date is not correct.

Example in Dell site :
![image](https://user-images.githubusercontent.com/3593751/219424529-4fe979a5-fd50-4752-9b3e-dbeaa11798f1.png)

In my GLPI : 
buy date : 24/09/2022
warranty start date : 25/09/2023
warranty end date : 25/09/2025
warranty duration : 24 month

**Comment by tsmr** [comment]
Try with 3.0.6 version of plugin
