### ISSUE TITLE
front/config.php does not show existing configurations

### ISSUE THREAD

**Issue by supertramp4** [InfotelGLPI/manufacturersimports#130]
* Version of the plugin : 3.0.4
* Version of your GLPI :  10.1.0-Dev ( Nightly build )
* Steps to reproduce (which actions have you made) :
goto Setup -> Plugins -> Supplier Imports -> (Actions) Configure
The page <site>/marketplace/manufacturersimports/front/config.php displays
however the screen is empty and it looks like the system does not have any configurations ( but it does) 

* Expected result :
Display a list of existing configurations

* Actual result :
Blank page
If however i manually goto the correct ID with URL 
<site>/marketplace/manufacturersimports/front/config.form.php?id=1
Then the page shows the configured data correctly

**Comment by tsmr** [comment]
Try with 3.0.6 version of plugin
