### ISSUE TITLE
older lenovo computers imports KO

### ISSUE THREAD

**Issue by AaBaboulinet** [InfotelGLPI/manufacturersimports#132]
Hello,

Here is my problem :

------------
* Version of the plugin : 3.0.5

* Version of your GLPI : 10.0.6

* Steps to reproduce (which actions have you made) : configure for DELL & LENOVO, then import warranty informations

* Expected result : all imports OK

* Actual result : DELL imports : OK, LENOVO imports : newest computers (ex : Thinkpad E14) imports OK but "older" computers (ex : thikpad yoga 370, thinkpad x270, thinkcentre M710q, thinkcentre M70q) imports are KO

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by tsmr** [comment]
Try with 3.0.6 version of plugin

**Comment by AaBaboulinet** [comment]
Thanks, it works with the new version.
