### ISSUE TITLE
Lenovo Import KO 14/02/2024

### ISSUE THREAD

**Issue by TpFi** [InfotelGLPI/manufacturersimports#133]
* Version of the plugin : 
3.0.5

* Version of your GLPI : 
10.0.12

* Steps to reproduce (which actions have you made) :
 - Configuration of the Lenovo import : 
![Capture1](https://github.com/InfotelGLPI/manufacturersimports/assets/160040105/662b4543-8b35-4703-a593-e011bd805d56)
 - Select of Lenovo :
![image](https://github.com/InfotelGLPI/manufacturersimports/assets/160040105/c05d754f-9e69-4307-a919-e6a6cf07b170)
 - Check everyone of the Lenovo computers and click on Submit :
![image](https://github.com/InfotelGLPI/manufacturersimports/assets/160040105/715fbb2d-5e27-420d-88e2-2b847bd566f8)

I tried with every manufacturers link : 
- https://supportapi.lenovo.com/v2.5/warranty
- https://supportapi.lenovo.com/v2.5/warranty?Serial=[SerialNumber]
- https://supportapi.lenovo.com/v2.5/warranty?Serial=
- https://pcsupport.lenovo.com/products//warranty

* Expected result :
Retrieve the end of the warranty date as shown in the picture below when you go in the website : 
![image](https://github.com/InfotelGLPI/manufacturersimports/assets/160040105/e8f07346-aacc-489a-9411-a4057ef64400)

* Actual result :
Import KO : 
![image](https://github.com/InfotelGLPI/manufacturersimports/assets/160040105/cc528c3b-9a6e-41ee-a23f-353fab5c0276)

* URL of the page :
http://192.168.100.22/glpi/marketplace/manufacturersimports/front/import.php

* Screenshot of the problem (if pertinent) :

**Comment by TpFi** [comment]
Good morning,

Has anyone read my topic ? I could use some help please :)

Cordially

**Comment by tsmr** [comment]
Try with 3.0.6 version of plugin
