### ISSUE TITLE
Automatic fetch warranty information

### ISSUE THREAD

**Issue by ViktorBackan** [InfotelGLPI/manufacturersimports#134]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 3.0.5

* Version of your GLPI : 10.0.12

* Steps to reproduce (which actions have you made) : -

* Expected result : automatic warranty fetching without having to manually click "Retrieve warranty form manufacturer"

* Actual result : Manual input needed

* URL of the page : - 

* Screenshot of the problem (if pertinent) :
* 
![image](https://github.com/InfotelGLPI/manufacturersimports/assets/162117772/2742b2eb-098e-487f-8612-d4e0629949c9)

**Comment by tsmr** [comment]
Hello

For Dell (only) you have an automatic actions for retrieve werranty :)

**Comment by ViktorBackan** [comment]
Cool thanks! I saw it was disabled and after activating it started filling automatically :)

Any plans on supporting more manufacturers? We mainly have Dells but some computers from other brands


​​​​​
Viktor

Backan

|

Lead corporate IT

at
Novotek AB

From: Xavier CAILLAUD ***@***.***>
Sent: Monday, 4 March 2024 14:56
To: InfotelGLPI/manufacturersimports ***@***.***>
Cc: Viktor Backan | Novotek Sweden ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [InfotelGLPI/manufacturersimports] Automatic fetch warranty information (Issue #134)


Hello

For Dell (only) you have an automatic actions for retrieve werranty :)

**Comment by tsmr** [comment]
Only Dell has a dedicated API :/
