### ISSUE TITLE
Unable to import HP computer

### ISSUE THREAD

**Issue by fred-lix** [InfotelGLPI/manufacturersimports#137]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 3.0.8

* Version of your GLPI : 10.0.15

* Steps to reproduce (which actions have you made) : import any HP computer

* Expected result : Import OK

* Actual result : "Problème lors de l'importation"

* URL of the page :

* Screenshot of the problem (if pertinent) :

Bonjour,

I am using the following settings : 
Url du fabricant : https://support.hp.com/fr-fr/check-warranty/
Adresse API du token d’accès : https://warranty.api.hp.com/oauth/v1/token
Adresse API des garanties : https://warranty.api.hp.com/productwarranty/v2/jobs
( I also tried https://warranty.api.hp.com/productwarranty/v2/queries )
Fournisseur affecté par défaut : HP
ID du client and Clé API secrète ; provide by Hp

Those settings are working with cURL Warranty API Sample Scripts

Thank you

Regards,

Frederic

**Comment by fred-lix** [comment]
sorry just found it is working after reset import before

**Comment by falco2001** [comment]
Good morning,
for me I don’t have a data import from HP: 
glpi 10.0.10 and plugin-in 3.0.8
I have: 
I am using the following settings :
Url du fabricant : https://support.hp.com/fr-fr/check-warranty/
Adresse API du token d’accès : https://warranty.api.hp.com/oauth/v1/token
Adresse API des garanties : https://warranty.api.hp.com/productwarranty/v2/jobs
( I also tried https://warranty.api.hp.com/productwarranty/v2/queries )
Vendor assigned by default: HP
Client ID and Secret API key; provide by Hp
Any idea?
Thank you

**Comment by LRYDark** [comment]
Bonjour à tous,

@falco2001 Je rencontre le même problème que vous, il ne se passe rien.
Url du fabricant : https://support.hp.com/fr-fr/check-warranty/
Adresse API du token d’accès : https://warranty.api.hp.com/oauth/v1/token
Adresse API des garanties : https://warranty.api.hp.com/productwarranty/v2/jobs

Avez-vous une solution ?

Merci

**Comment by fred-lix** [comment]
Bonjour,

Do you try form "Imports fabricants" from the tool menu ?

You sould get a page where you need to select Computer / HP / non 
imported equipements
(sorry my gui is in French)

**Comment by falco2001** [comment]
Good morning,

This is the use via an import in a computer file.

In fact nothing works.

I did a curl test and via rest of firefox it works via a token then via a jobs then another url ...

Thank you
May be version of glpi??? 10.0.10

**Comment by falco2001** [comment]
Good morning,
I just installed a dev platform in 10.0.15 ditto! nothing works . Thank you

**Comment by Anonymenet77** [comment]
Hello,

I'm reaching out to ask how you were able to obtain your Client ID and API key.

I contacted the following address: warrantyapi.customers@hp.com, but they informed me that they no longer provide API keys.

Would you have a contact you could recommend, or could you explain the process you followed to obtain this information?

Thank you in advance for your help.

Best regards,

**Comment by falco2001** [comment]
Hello,
go to the https://developers.hp.com/user page create yb account and create its API access. It takes a few days or more to get API access.
However, the HP site is often down and in addition API access are valid for 2 months! 
For DELL the API access is valid all the time and it works with HP nothing works via GLPI

**Comment by Anonymenet77** [comment]
Hi Falco,

Thank you for your reply.

I’ve reached this page, but I’m wondering if there’s anything else I need to do, or should I just wait for a key to appear under "My API Credential"?

![image](https://github.com/user-attachments/assets/84a130d7-22e4-4e26-a6c2-fae849a32591)

Is the plugin still maintained? It seems like there hasn’t been much activity for a while, and there doesn’t seem to be any alternative available, which would be a real shame.

Thanks in advance for your feedback.

**Comment by falco2001** [comment]
Si il faut créer une api :
![image](https://github.com/user-attachments/assets/936dd84f-6121-4eff-835f-a643b8e23166)

**Comment by Anonymenet77** [comment]
I'm sorry, could you please clarify from where I should start creating the API?

**Comment by falco2001** [comment]
https://developers.hp.com/hp-warranty-api-registration-page

**Comment by Anonymenet77** [comment]
:(

![image](https://github.com/user-attachments/assets/322f1f66-0986-49e7-850b-6619b935d6e1)

**Comment by falco2001** [comment]
https://developers.hp.com/hp-warranty-api

**Comment by Anonymenet77** [comment]
lol

![image](https://github.com/user-attachments/assets/b586e626-4bee-495b-8819-2c5b7bdaa59f)

**Comment by tsmr** [comment]
#French#
Faire une demande d'accès à l'API via son HP account manager / commercial HP
L'account manager va rentrer la demande dans le système HP et donner quelques informations sur son client
Le client recevra un email de la part de l'adresse warrantyapi.customers@hp.com avec les étapes à effectuer pour finaliser sa demande et avoir l'accès
La clé est valable 90 jours
Un email sera envoyé à l'utilisateur quand il faudra renouveler cette clé ; l'email contient un lien sur lequel cliquer pour générer de nouvelles clés. C'est une démarche rapide. 

#English#
Request access to the API via your HP account manager / HP sales representative
The account manager will enter the request into the HP system and provide some information about their customer
The customer will receive an email from warrantyapi.customers@hp.com with the steps to complete their request and gain access
The key is valid for 90 days
An email will be sent to the user when this key needs to be renewed; the email contains a link to click on to generate new keys. This is a quick process.
