### ISSUE TITLE
GLPI stop responding during import

### ISSUE THREAD

**Issue by mathieuchateau** [InfotelGLPI/manufacturersimports#15]
When doing an import, for example 250 computers, GLPI is not responding to any web request during import. Even access to home page is pending (browser loading page forever).

I checked MySQL, not a single query running that could lock table.

If it's not MySQL which is locked, what is locking whole GLPI?

250 computers import mean around 660 seconds without GLPI responding to users and helpdesk..

Thanks

**Comment by boscorelly** [comment]
Ton serveur web fait des requetes à distances, et attend la réponse. A chaque réponse il check et update ou pas la database.
Il faut donc prendre en compte ce temps là. 660 secondes pour 250 machines, ça donne 2.64 secondes par machine. C'est pas énorme.
C'est quoi les machines ? Dell ?

**Comment by mathieuchateau** [comment]
oui des Dell
A priori ca ne bloque en fait que ma session, d'autres peuvent se connecter ou moi mais avec un autre navigateur

**Comment by boscorelly** [comment]
c'est normal que ça "bloque" : le navigateur attends la fin de la réponse du serveur :)

**Comment by mathieuchateau** [comment]
Oui mais idem en ouvrant d'autres onglets

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2016-12-13 13:30 GMT+01:00 Camille Ollié <notifications@github.com>:
