### ISSUE TITLE
Fujitsu import is not longer working because vendor database not available

### ISSUE THREAD

**Issue by maikst** [InfotelGLPI/manufacturersimports#16]
If you try to import warranty data for Fujitsu there is only a msg like this:

Error: Warranty Database Unavailable

This message comes for weeks now.
It seems that the page is not longer maintained?
The script is using: http://sali.uk.ts.fujitsu.com/ServiceEntitlement/service.asp

The warranty data and more is still available via
http://support.ts.fujitsu.com/IndexWarranty.asp?lng=EN

But I have no glue how to implement it.

Please check.
Thank you for your nice plugin!

**Comment by maikst** [comment]
Any intention change?
The plugin is useless for us without Fujitsu Warranty Info.

I found the page where the actual warranty infos are still available.

Result with sample No YLPV053009
https://support.ts.fujitsu.com/Warranty/WarrantyStatus.asp?lng=DE&IDNR=YLPV053009&HardwareGUID=&Version=3.5

Shouldn't be too difficult to get the few data from this page. I hope.

Thanks,
Maik

**Comment by tsmr** [comment]
Yes now we can test to retrieve data from this page

**Comment by maikst** [comment]
Thank you.

It worked for most systems but not for all?!

Example SN which was working: YLTH219440

But this one not: YLPV052741
The product description is longer (ESP P7936 ESTAR5 /C2D E7500/2GB/DVD/) 
Maybe this is the reason?

Anyway: great work ! Thank you! Merci beaucoup :-)

Best Regards,
Maik

**Comment by tsmr** [comment]
No problem for me for serial YLPV052741
