### ISSUE TITLE
Dell parameters not taken into account and Dell code not called.

### ISSUE THREAD

**Issue by stephanemouton** [InfotelGLPI/manufacturersimports#19]
I enter Dell parameters in the configuration screen and I can see that those parameters are not used. It is the hard coded values in inc/dell.class.php which are used instead.
I modified the latter values and got the right URL.
In addition it seems that result decoding is not called (i added logs in dell.class.php and they were nether called).
I'd like to know how and where in the code the plugin decides to call manufacturer specific code. With this information I could contribute to code of the plugin so that Dell code is called.

**Comment by boscorelly** [comment]
Update your version, and use the appropriate version of API calling : https://sandbox.api.dell.com/support/assetinfo/v4/getassetwarranty/ (or without sandbox)

**Comment by amma35** [comment]
This has been changed in this correction: see #16
The url that will be called will be the one specified in the configuration.
