### ISSUE TITLE
Dell Warranty Lookup : Weird result for some HW with extended warranty

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/manufacturersimports#2]
for some HW, the Dell Warranty WS is giving weird result :
`
<GetAssetInformationResult>
<Asset>
<AssetHeaderData>
<ServiceTag>4ZC9R4J</ServiceTag>
<SystemID>pwe_m610</SystemID>
<Buid>2727</Buid>
<Region>Europe</Region>
<SystemType>PowerEdge</SystemType>
<SystemModel>M610</SystemModel>
<SystemShipDate>2010-05-12T20:00:00-05:00</SystemShipDate>
</AssetHeaderData>
<Entitlements>
<EntitlementData>
<Provider/>
<StartDate>2013-07-04T00:00:00</StartDate>
<EndDate>2013-12-31T00:00:00</EndDate>
<DaysLeft>32</DaysLeft>
<EntitlementType>Active</EntitlementType>
</EntitlementData>
<EntitlementData>
<Provider/>
<StartDate>2013-07-04T00:00:00</StartDate>
<EndDate>2013-12-31T00:00:00</EndDate>
<DaysLeft>32</DaysLeft>
<EntitlementType>Active</EntitlementType>
</EntitlementData>
<EntitlementData>
<Provider/>
<StartDate>2010-05-12T00:00:00</StartDate>
<EndDate>2013-05-13T00:00:00</EndDate>
<DaysLeft>0</DaysLeft>
<EntitlementType>Expired</EntitlementType>
</EntitlementData>
<EntitlementData>
<Provider/>
<StartDate>2010-05-12T00:00:00</StartDate>
<EndDate>2013-05-13T00:00:00</EndDate>
<DaysLeft>0</DaysLeft>
<EntitlementType>Expired</EntitlementType>
</EntitlementData>
<EntitlementData>
<Provider/>
<StartDate>2011-09-22T00:00:00</StartDate>
<EndDate>2012-09-23T00:00:00</EndDate>
<DaysLeft>0</DaysLeft>
<EntitlementType>Expired</EntitlementType>
</EntitlementData>
</Entitlements>
</Asset>
</GetAssetInformationResult>
`

According to this example, the current version of the plugin will extract "<StartDate>2011-09-22T00:00:00</StartDate>" as to be the Start date of Warranty. Let us discuss to see if it makes more sense to use "<SystemShipDate>2010-05-12T20:00:00-05:00</SystemShipDate>" instead.

For the weird result, Dell seems to answer duplicate warranty information (See the 2 first <EntitlementData> objects in example).

Global proposal:
Start date : Use SystemShipDate?
Warranty duration : What about picking the oldest date within all the <EntitlementData> objects and then calculate from the SystemShipDate?

**Comment by bacus99** [comment]
Change dell.class.php, line 69 to 80 I think.  Works for me

   function getBuyDate($contents) {
      $info = json_decode($contents, TRUE);
      if(isset($info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["ShipDate"])) {
         if(isset($info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["ShipDate"])) {
            return $info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["ShipDate"];
         } else {
            return $info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["Warranties"]["Warranty"][0]["StartDate"];
         }
      }
      
      return false;
   }

**Comment by tomolimo** [comment]
Should be fixed in #22
