### ISSUE TITLE
Where is gone getWarrantyInfo feature that was present in 1.5.2?

### ISSUE THREAD

**Issue by tomolimo** [InfotelGLPI/manufacturersimports#23]
Where is gone getWarrantyInfo feature that was present in 1.5.2?

**Comment by tsmr** [comment]
??

**Comment by tomolimo** [comment]
Ok, forget this issue, I've found where it's coming: that was my own dev last year.
Sorry for posting this issue.
I'll push a PR for this feature.
Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
PR done see #24
