### ISSUE TITLE
erreur lors de l'import avec le Plugin Manufacturers Web Import Api V4 Dell

### ISSUE THREAD

**Issue by imatechamabon** [InfotelGLPI/manufacturersimports#25]
Bonjour,
J’ai modifié le fichier dell.class.php en suivant cette page : https://github.com/InfotelGLPI/manufacturersimports/pull/22/files

A priori, l’accès au Webservices dell fonctionne mais j’ai l’erreur suivante :

This XML file does not appear to have any style information associated with it. The document tree is shown below

Voir fichier joint

y-a-t-il une autre modification à effectuer ?

En vous remerciant
![bugimport](https://cloud.githubusercontent.com/assets/20859326/18084097/3396688a-6ea6-11e6-940e-7f42afffe8dd.PNG)

**Comment by tsmr** [comment]
La meilleure solution est de mettre à jour le plugin : 
https://github.com/InfotelGLPI/manufacturersimports/releases/tag/1.8.1
