### ISSUE TITLE
Lenovo :  cannot import Warranties 

### ISSUE THREAD

**Issue by denisit29** [InfotelGLPI/manufacturersimports#26]
Hi,
Lenovo import doesn't work anymore (I upgraded to 1.8.1).
Thanks.

**Comment by tsmr** [comment]
This is a access problem to Lenovo web site : 

With this address : 

http://shop.lenovo.com/SEUILibrary/controller/e/frweb/LenovoPortal/fr_FR/config.workflow:ContinueWarranty?country-code=897&serial-number=LRCBTCE&machine-type=2597-67G&btnSubmit

No problem
