### ISSUE TITLE
Fujitsu not working

### ISSUE THREAD

**Issue by boscorelly** [InfotelGLPI/manufacturersimports#27]
Fuji is no more working. "Aucun fabricant utilisable. Merci de configurer au moins un fabricant"

**Comment by tsmr** [comment]
You must setup the supplier into the plugin.

**Comment by boscorelly** [comment]
I have re checked how to use today.
I was not using it as it's intended to.

But i have an error : 
https://support.ts.fujitsu.com/Warranty/WarrantyStatus.asp?lng=EN&IDNR=YM4P066448&HardwareGUID=&Version=3.5

Post-Import
Nom	Numéro de série	Lien	Résultat	Détails
TRJ16-DT-001
YM4P066448	Fabricant	Import KO (2016-11-14)	
Nombre total de matériel importés 0

**Comment by boscorelly** [comment]
Il y a bien à la base un problème avec le plugin. Il chercher "Service en date" mais c'est cela qu'il y a dans le code :
`<tr>
								<td>&nbsp;</td>
								<td class="contenthead">Warranty / Service start date</td>
								<td class="contenthead">Warranty end date</td>
								<td class="contenthead">End of Product Support</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td class="contenttext">10/10/2014</td>
								<td class="contenttext">10/10/2015</td>
								<td class="contenttext">Not yet defined</td>
							</tr>
`
