### ISSUE TITLE
List configuration error

### ISSUE THREAD

**Issue by boscorelly** [InfotelGLPI/manufacturersimports#33]
GLPI 9.1.1
Manufacturerimports 1.9.0

2017-01-06 14:53:44 [153@STSRV2K8_ING]
  *** MySQL query error:
  SQL: SELECT \'coe\' AS currentuser,
                        `glpi_plugin_manufacturersimports_configs`.`entities_id`, `glpi_plugin_manufacturersimports_configs`.`is_recursive`,  `glpi_plugin_manufacturersimports_configs`.`name` AS `ITEM_0`,
                        `glpi_plugin_manufacturersimports_configs`.`id` AS `ITEM_0_id`,
                        
                        `glpi_entities`.`completename` AS `ITEM_1`,  `glpi_manufacturers`.`dropdown` AS `ITEM_2`,  `glpi_plugin_manufacturersimports_configs`.`id` AS id  FROM `glpi_plugin_manufacturersimports_configs`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_plugin_manufacturersimports_configs`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_plugin_manufacturersimports_configs`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              ) WHERE   (  1 )  ORDER BY ITEM_0 ASC  LIMIT 0, 35
  Error: Unknown column 'glpi_manufacturers.dropdown' in 'field list'
  Backtrace :
  inc\search.class.php:921                           
  inc\search.class.php:97                            Search::constructDatas()
  inc\search.class.php:80                            Search::showList()
  plugins\manufacturersimports\front\config.php:37   Search::show()

**Comment by amma35** [comment]
You can make the correction of the file inc/config.class.php to correct this bug by referring to the commit carried out above.
Thank you

**Comment by boscorelly** [comment]
Thanks !
