### ISSUE TITLE
Import HP Wrong DATA

### ISSUE THREAD

**Issue by Wedge82** [InfotelGLPI/manufacturersimports#36]
Hello
- The version of the plugin 1.9.1
- The version of your GLPI 9.1.2
- The steps to reproduce your issue :

If click on "information fabriquants" link, i can see the warranty is expired :
![image](https://cloud.githubusercontent.com/assets/25956152/23213510/7e092f0c-f90b-11e6-8cbc-115f4340b4e6.png)

If i import the computer i can see that :
![image](https://cloud.githubusercontent.com/assets/25956152/23213576/ba02c6ee-f90b-11e6-8ce9-a728f143f417.png)

So all the data i import are wrong :(

regards

**Comment by amma35** [comment]
Hi,

A new version of the plugin will soon be released and this version should correct this problem.
Which url do you use to import HP warranties?

**Comment by amma35** [comment]
see https://github.com/InfotelGLPI/manufacturersimports/releases/tag/1.9.1
