### ISSUE TITLE
Dell API sandbox option

### ISSUE THREAD

**Issue by tyronewyatt** [InfotelGLPI/manufacturersimports#37]
Could you create an option to allow the manufacture Dell to use sandbox mode?

I have recently signed up for Dell TechDirect in order to create a warranty API.

The Dell warranty API it won't work in the plugin. 
![image](https://cloud.githubusercontent.com/assets/13756677/23572376/d63adbc6-00c2-11e7-9bdd-704be563283c.png)

If I click on the manufacture link I get the following.
![image](https://cloud.githubusercontent.com/assets/13756677/23572196/8626f922-00c1-11e7-97f0-9895b32e3268.png)

Reading over the email from Dell the warranty API initially only works on sandbox servers. 
![image](https://cloud.githubusercontent.com/assets/13756677/23572175/6de59b70-00c1-11e7-85b7-457bf121f751.png)

If you create an option to enable sandbox it would be easier for testing the new Dell warranty APIs.

Please refer to email from Dell...

"Dear Customer,
 
We have processed your “Warranty Status V4 API” request and below is the API key for your use.
 
Warranty V4 API Key :    

Initially it is for use in our sandbox environment. Post successful testing in Sand Box , your key will be promoted to production. Would appreciate if you can keep us posted once you complete Sandbox testing.
In another email you will receive an attached zip file with documentation, sample code, and a license agreement file.  Please read and review the license agreement file. Inside that agreement is a password to unlock the SDK files from the zip archive. By entering the password to decrypt and open the API SDK zip file, Dell and Customer,  intending to be legally bound, agree to all of the provisions of this Agreement. 
 
Sandbox API End Point URL :  https://sandbox.api.dell.com or https://sandbox.apidp.dell.com ( The SDK document references production end point(s). You need to change  https://api.dell.com  to https://sandbox.api.dell.com or  https://sandbox.apidp.dell.com for testing in Sandbox). If you need any technical assistance reach out to APIs_TechDirect@Dell.com
 
NOTE: This API key will remain active for 90 days. If it has not been certified for production within this time period, it will be deactivated. API key extensions are possible if your project so requires. Please contact the API team at APIs_TechDirect@Dell.com for key extension requests.
 
Thanks & Regards,
Dell"

Regards,
Tyrone Wyatt

**Comment by amma35** [comment]
This feature is already developed for the plugin version 1.9.1.

The release for the 1.9.1 version should come out soon.

**Comment by tyronewyatt** [comment]
Cool thanks :)
