### ISSUE TITLE
Issue to import some Dell computers

### ISSUE THREAD

**Issue by miambe** [InfotelGLPI/manufacturersimports#38]
GLPI 9.1.3 / Plugin manufacturersimports 1.9.0
I've successfully imported more than 100 Dell computers using the plugin but with 23 of them I'm getting "Problem during the importation"

I don't have any idea what's wrong as the answer from Dell is correct (we have all the information, may be the ServiceLevelDescription answer is too long ? 
If I check the MySQL table glpi_infocoms it doesn't seems to be too long as:
| warranty_info     | varchar(255)  | YES  |     | NULL    |                |
and "Onsite Service After Remote Diagnosis (Consumer Customer)/ Next Business Day Onsite After Remote Diagnosis (Commercial Customer)" is only 128 characters.

Here is the answer from 2 requests:
Request 1:
 `<AssetWarrantyDTO xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Dell.Support.AssetsExternalAPI.Web.Models.V1.Response"><AdditionalInformation i:nil="true" /><AssetWarrantyResponse><AssetWarrantyResponse><AssetEntitlementData><AssetEntitlement><EndDate>2014-11-30T17:59:59</EndDate><EntitlementType>INITIAL</EntitlementType><ItemNumber>709-10557</ItemNumber><ServiceLevelCode>ND</ServiceLevelCode><ServiceLevelDescription>Onsite Service After Remote Diagnosis (Consumer Customer)/ Next Business Day Onsite After Remote Diagnosis (Commercial Customer)</ServiceLevelDescription><ServiceLevelGroup>5</ServiceLevelGroup><ServiceProvider i:nil="true" /><StartDate>2011-11-29T18:00:00</StartDate></AssetEntitlement><AssetEntitlement><EndDate>2014-11-30T17:59:59</EndDate><EntitlementType>INITIAL</EntitlementType><ItemNumber>712-10549</ItemNumber><ServiceLevelCode>CC</ServiceLevelCode><ServiceLevelDescription>Complete Care / Accidental Damage</ServiceLevelDescription><ServiceLevelGroup>11</ServiceLevelGroup><ServiceProvider i:nil="true" /><StartDate>2011-11-29T18:00:00</StartDate></AssetEntitlement><AssetEntitlement><EndDate>2014-11-30T17:59:59</EndDate><EntitlementType>INITIAL</EntitlementType><ItemNumber>710-18618</ItemNumber><ServiceLevelCode>NU</ServiceLevelCode><ServiceLevelDescription>Next Business Day ProSupport</ServiceLevelDescription><ServiceLevelGroup>5</ServiceLevelGroup><ServiceProvider i:nil="true" /><StartDate>2011-11-29T18:00:00</StartDate></AssetEntitlement></AssetEntitlementData><AssetHeaderData><BUID>2828</BUID><CountryLookupCode>BE</CountryLookupCode><CustomerNumber>2976815</CustomerNumber><IsDuplicate>false</IsDuplicate><ItemClassCode>RS004</ItemClassCode><LocalChannel>11150</LocalChannel><MachineDescription>Latitude E6420</MachineDescription><OrderNumber>622989590</OrderNumber><ParentServiceTag i:nil="true" /><ServiceTag>C9B66R1</ServiceTag><ShipDate>2011-11-29T18:00:00</ShipDate></AssetHeaderData><ProductHeaderData><LOB>Latitude</LOB><LOBFriendlyName>Latitude</LOBFriendlyName><ProductFamily>Laptops</ProductFamily><ProductId>latitude-e6420</ProductId><SystemDescription>Latitude E6420</SystemDescription></ProductHeaderData></AssetWarrantyResponse></AssetWarrantyResponse><ExcessTags><BadAssets xmlns:d3p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" /></ExcessTags><InvalidBILAssets><BadAssets xmlns:d3p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" /></InvalidBILAssets><InvalidFormatAssets><BadAssets xmlns:d3p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" /></InvalidFormatAssets></AssetWarrantyDTO>`

Request 2:

`<AssetWarrantyDTO xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Dell.Support.AssetsExternalAPI.Web.Models.V1.Response"><AdditionalInformation i:nil="true" /><AssetWarrantyResponse><AssetWarrantyResponse><AssetEntitlementData><AssetEntitlement><EndDate>2014-06-23T18:59:59</EndDate><EntitlementType>INITIAL</EntitlementType><ItemNumber>710-18618</ItemNumber><ServiceLevelCode>NU</ServiceLevelCode><ServiceLevelDescription>Next Business Day ProSupport</ServiceLevelDescription><ServiceLevelGroup>5</ServiceLevelGroup><ServiceProvider i:nil="true" /><StartDate>2011-06-22T19:00:00</StartDate></AssetEntitlement><AssetEntitlement><EndDate>2014-06-23T18:59:59</EndDate><EntitlementType>INITIAL</EntitlementType><ItemNumber>712-10549</ItemNumber><ServiceLevelCode>CC</ServiceLevelCode><ServiceLevelDescription>Complete Care / Accidental Damage</ServiceLevelDescription><ServiceLevelGroup>11</ServiceLevelGroup><ServiceProvider i:nil="true" /><StartDate>2011-06-22T19:00:00</StartDate></AssetEntitlement><AssetEntitlement><EndDate>2014-06-23T18:59:59</EndDate><EntitlementType>INITIAL</EntitlementType><ItemNumber>709-10557</ItemNumber><ServiceLevelCode>ND</ServiceLevelCode><ServiceLevelDescription>Onsite Service After Remote Diagnosis (Consumer Customer)/ Next Business Day Onsite After Remote Diagnosis (Commercial Customer)</ServiceLevelDescription><ServiceLevelGroup>5</ServiceLevelGroup><ServiceProvider i:nil="true" /><StartDate>2011-06-22T19:00:00</StartDate></AssetEntitlement></AssetEntitlementData><AssetHeaderData><BUID>808</BUID><CountryLookupCode>DE</CountryLookupCode><CustomerNumber>4943483</CustomerNumber><IsDuplicate>false</IsDuplicate><ItemClassCode>RS004</ItemClassCode><LocalChannel>IEM00</LocalChannel><MachineDescription>Latitude E6420</MachineDescription><OrderNumber>67855791</OrderNumber><ParentServiceTag i:nil="true" /><ServiceTag>3W6L2Q1</ServiceTag><ShipDate>2011-06-22T19:00:00</ShipDate></AssetHeaderData><ProductHeaderData><LOB>Latitude</LOB><LOBFriendlyName>Latitude</LOBFriendlyName><ProductFamily>Laptops</ProductFamily><ProductId>latitude-e6420</ProductId><SystemDescription>Latitude E6420</SystemDescription></ProductHeaderData></AssetWarrantyResponse></AssetWarrantyResponse><ExcessTags><BadAssets xmlns:d3p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" /></ExcessTags><InvalidBILAssets><BadAssets xmlns:d3p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" /></InvalidBILAssets><InvalidFormatAssets><BadAssets xmlns:d3p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" /></InvalidFormatAssets></AssetWarrantyDTO>`

**Comment by amma35** [comment]
Hello,

I just tested with the serial numbers of your two examples it works on my side.

Do you have any errors when running both computers?

**Comment by amma35** [comment]
I close the issue without answer.

**Comment by Alwaysin** [comment]
I have the same problem with only some Service Tag... No error on apache2 side.
