### ISSUE TITLE
Prise en compte des extension de garantie

### ISSUE THREAD

**Issue by jettarse52** [InfotelGLPI/manufacturersimports#39]
Bonjour,

J'ai testé le plugin et je suis confronté a un problème.

La garantie importé dans glpi est seulement la garantie constructeur (1 an).

Or nous avons une garantie supplémentaire de 4 ans enregistrée et bien bu sur la page du constructeur.
Est il possible de prendre celle ci en compte pour que nos informations de garantie soit correcte ?

Merci

**Comment by boscorelly** [comment]
Bonjour,

pour quel constructeur ?

**Comment by amma35** [comment]
Bonjour,

@jettarse52 pour quel constructeur l'extension de garantie ne fonctionne pas ?

**Comment by Langelot007** [comment]
Je pense que c'est pour Lenovo :) J'ai le même soucis ! 
Il y a 2 champs : 
"expirationDate":"10/29/15"
"upgrade_expirationDate":"10/29/17"
J'imagine qu'il faut modifier dans "lenovo.class.php"

J'ai modifier la ligne 121 comme suit : 
$myDate = trim($contents['upgrade_expirationDate']);

cela me remonte bien ma garantie de 36 mois.
mais il faudrait PT faire 1 champs supplémentaire sur l'affichage dans "gestion" par exemple : 

Date de début de garantie 
Durée de garantie "base" 12 mois Expirant le 29-10-2015
Durée de "l'extension de garantie" 24 mois Expirant le 29-10-2017
Informations sur la garantie

Merci.
