### ISSUE TITLE
Dell mauvaise date de début de garantie

### ISSUE THREAD

**Issue by bacus99** [InfotelGLPI/manufacturersimports#4]
Bonjour,

J'ai corrigé le code pour la date de début de Dell.  Fonctionne maintenant dans mon environmenent

Je cherche juste comment vous faire parvenir le tout

Dell.class.php

Ligne 68 - 80

   
   function getBuyDate($contents) {
      $info = json_decode($contents, TRUE);
      if(isset($info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["ShipDate"])) {
         if(isset($info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["ShipDate"])) {
            return $info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["ShipDate"];
         } else {
            return $info["GetAssetWarrantyResponse"]["GetAssetWarrantyResult"]["Response"]["DellAsset"]["ShipDate"];
         }
      }
      
      return false;
   }

Christian

**Comment by tomolimo** [comment]
Should be fixed by #22
