### ISSUE TITLE
Lenovo import not working

### ISSUE THREAD

**Issue by Tomiliy** [InfotelGLPI/manufacturersimports#40]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin. : 9.1.2
- The version of your GLPI.: 1.9.0
- The steps to reproduce your issue.: Every tiei try to discover some Lenovo Laptops (460, 470 or anything else.. Nothing happend.  excpet an error: Problem during the importation

is there a Logfile? Is the URL wrong, where i ask fpr the Lenovos?

Thank you
Thomas

**Comment by tsmr** [comment]
For development : We will try with http://www3.lenovo.com/fr/fr/warranty-upgrades/?serial-number=XXXXXX

**Comment by WooboyTW** [comment]
I had updated query URL
please see the pull request
https://github.com/InfotelGLPI/manufacturersimports/pull/41

**Comment by Tomiliy** [comment]
what do you mean?
where can i change the query Url and how?
and in what should i change the Query URL?
Thanks

**Comment by amma35** [comment]
Changes have to be made in this code.
The url is to change in the configuration of the manufacturer where it is necessary to specify the url of the manufacturer.

**Comment by Tomiliy** [comment]
Ok, i'm no programmer...
Which code is to change, where and in what?
actually the program is not working..... alle questions are false...
What exactly is to do for a proper work like before?

Thanks

**Comment by amma35** [comment]
The code will be modified at the moment it does not work.

**Comment by Tomiliy** [comment]
Ah, ok...
when do you think the new, functional version is ready to deliver?

**Comment by amma35** [comment]
I'm waiting for the changes on @WooboyTW 's part in relation to his pull request.
