### ISSUE TITLE
I don't see HP in default manufacturer

### ISSUE THREAD

**Issue by G1hicius** [InfotelGLPI/manufacturersimports#42]
Hello team,

- The version of the plugin :  1.9.0
- The version of your GLPI : 9.1.5
- The steps to reproduce your issue : I've just installed your plug-in but when I want to configure manufacturer, by default I just have DELL / FUJITSU / LEVOVO / TOSHIBA, but I don't see  HP. Is it normal?

And just another question. I don't see a manual to explain how it works

best regards... and sorry ofr my poor English! :)

**Comment by amma35** [comment]
HP did not work in this release due to manufacturer changes on their site.
It works a little better on this release:https://github.com/InfotelGLPI/manufacturersimports/releases/tag/1.9.1

At the moment no documentation has been created.

**Comment by G1hicius** [comment]
OK I've Hp now! 

Thanks you every much!!! :) 

have a good day! 

----- Mail original -----

De: "Amandine Manceau" <notifications@github.com> 
À: "InfotelGLPI/manufacturersimports" <manufacturersimports@noreply.github.com> 
Cc: "G1hicius" <sebastien.gelly@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 4 Octobre 2017 10:26:09 
Objet: Re: [InfotelGLPI/manufacturersimports] I don't see HP in default manufacturer (#42) 


HP did not work in this release due to manufacturer changes on their site. 
It works a little better on this release: https://github.com/InfotelGLPI/manufacturersimports/releases/tag/1.9.1 
At the moment no documentation has been created.
