### ISSUE TITLE
Fujitsu import isn't working in 2.0 

### ISSUE THREAD

**Issue by 005Zenturio** [InfotelGLPI/manufacturersimports#45]
Hi,

i tried to use the last Version of the Plugin (2.0) with GLPI 9.2.1.

If i try to add a new manufactuere "Fujitsu" he do not take any values from the template defined in inc\fujitsu.class.php.

I figured out that if i remove the // (comment) on line 96 in inc/config.class.php than I'm able to get the values from the template and the config line is saved with the name Fujitsu instead of 1,2,3 ...

But if i try to Import Warrenty Informations all i got is this: "Import failed (2017-12-29)"

Kind Regards

Andreas

**Comment by amma35** [comment]
Hi,
Fujitsu is in comment in the configuration because it does not work, this is normal.

**Comment by 005Zenturio** [comment]
Hi,

okay the reason is that the url din't response any usefull data exactly. 

So i figured out the neccesary steps to get the Informations. 

1.) Request this url: 
http://support.ts.fujitsu.com/include/Suchfunktion.asp?lng=EN&GotoURL=IndexWarranty&Search=YL3M032662

2.) From the response we need the HardwareGUID:
```
...
		hiddenField.setAttribute("name", "HardwareGUID");
		hiddenField.setAttribute("value", "F4256E09-11D4-45C8-B99E-1C70C5395D8B");
...
```

3.) With the HardwareGUID and the IDNR we are able to get the WarrentyData:

http://support.ts.fujitsu.com/Warranty/WarrantyStatus.asp?lng=com&IDNR=YL3M032662&HardwareGUID=F4256E09-11D4-45C8-B99E-1C70C5395D8B&Version=3.51

**Comment by amma35** [comment]
Hi,
Thank you for your feedback with this information.
The first url I am redirected to the homepage.
How will you retrieve the information from "HardwareGUID"?

However, the link does not take warranty extensions.

**Comment by 005Zenturio** [comment]
Hm,

thy changed the Site again i think, if you would open te first link its not an redirect to the homepage for me. I can choose the country, an than i get the warrenty informations.

If you have a look at the source of the page you will find the the link with the HardwareGUID: 
/Warranty/WarrantyStatus.asp?lng=COM&IDNR=YL3M032662&
HardwareGUID=F4256E09-11D4-45C8-B99E-1C70C5395D8B&Version=3.6'

Regex sould do the job :-).

R,

Andreas

**Comment by amma35** [comment]
Hi,

With the link "http://support.ts.fujitsu.com/Warranty/WarrantyStatus.asp?lng=COM&IDNR=YL3M032662&HardwareGUID=F4256E09-11D4-45C8-B99E-1C70C5395D8B&Version=3.6", I get a blank page.

It isn't possible to make the selection of the country in curl that is why with the link it is necessary to arrive directly on the page with the information of the guarantee. Without this access to the page without action, it isn't possible to recover the warranty information. 

If you have successfully recovered the warranty information with the import in curl, you can propose a solution.

**Comment by joschi99** [comment]
Any news about this issue? Problem seem's still unresolved until yet. Can I help in some way?

Regards,
Jochen

**Comment by 005Zenturio** [comment]
Hi Again,
sorry for the delay. 

I managed to write this as an proxy between imort an fujitsu. This works but im not able to get this in the plugin sorry :-(.
May it helps.

```
<?php
// create curl resource
        $ch = curl_init();
        $IDNR = $_GET['IDNR'];
        // set url
        curl_setopt($ch, CURLOPT_URL, "http://support.ts.fujitsu.com/include/Suchfunktion.asp?lng=de&GotoURL=IndexWarranty&Search=" . $IDNR);

        //return the transfer as a string
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)");
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_COOKIEFILE, "cookiefile");
        curl_setopt($ch, CURLOPT_COOKIEJAR, "cookiefile"); // SAME cookiefile

         curl_setopt($ch, CURLOPT_HTTPHEADER, ["Content-Type:application/x-www-form-urlencoded"]);
        // $output contains the output string
        $output = curl_exec($ch);
         curl_setopt($ch, CURLOPT_URL, "http://support.ts.fujitsu.com/Warranty/WarrantyStatus.asp?lng=com&IDNR=" . $IDNR . "&Version=3.6");
        $output = curl_exec($ch);

        print $output;

?>
```
