### ISSUE TITLE
Extension garantie Lenovo

### ISSUE THREAD

**Issue by Soffootix42** [InfotelGLPI/manufacturersimports#46]
Bonjour,

la prise en compte des extensions de garantie pour les ordinateurs de la marque LENOVO ne sont pas prise en compte.
Ils affichent une garantie de 12 mois alors que les postes ont une extension de garantie.

Merci d'avance
Soffootix

**Comment by Langelot007** [comment]
https://github.com/InfotelGLPI/manufacturersimports/issues/39

problème déjà remonter :)

**Comment by amma35** [comment]
Duplicate
