### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by arnomo** [InfotelGLPI/manufacturersimports#47]
GLPI 0.9
manufactuersimport 1.8.0 (i have tried 1.8.1 too)
Install Ok,
API Connect Ok,

i don't have all information when i want to import all Dell computer.
 When i click on Supplier information link, i have all information. But on GLPI no

Supplier : Dell Inc.
ShipDate : is empty
Warranty start : is empty
Warranty time : 12 month
Warranty end : is empty

Thanks for you feed back

**Comment by amma35** [comment]
Do you have examples of the information you see in the link? 
Do you have log errors when importing? (glpi/files/_log/php-errors.log and sql-errors.log)

**Comment by amma35** [comment]
I'm closing for now, feel free to reopen if issue persists.
