### ISSUE TITLE
Dell API key trunkated

### ISSUE THREAD

**Issue by samuel-halin** [InfotelGLPI/manufacturersimports#48]
Hello,

I'm using manufacturersimports 2.0.0 with glpi 9.2.2

The API key given by DELL is 36 character long. When I enter it in the appropriate field, it's trunkated to 32 character as soon as I save. Because of that, manufacturer import doesn't work.

Is there a way to fix it?
Thanks in advance

**Comment by amma35** [comment]
it's fixed in https://github.com/InfotelGLPI/manufacturersimports/issues/44
