### ISSUE TITLE
Selection too large, massive action disabled.

### ISSUE THREAD

**Issue by Alwaysin** [InfotelGLPI/manufacturersimports#49]
- The version of the plugin : 2.0.0
- The version of your GLPI : 9.2.1
- The steps to reproduce your issue :

Select Computers -> Dell -> Devices not imported

23 records are displayed, and at the bottom I see "Selection too large, massive action disabled."

**Comment by Alwaysin** [comment]
By displaying only 5 items I can import them, strange that 23 are considered "too much". There might be a bug with the display that is at 10000 by default and maybe the plugin thinks there really are 10000 of them.

**Comment by amma35** [comment]
This message is displayed when the PHP variable (max_input_vars) is smaller than the parameter you specified in the general configuration "Default search results limit (page)".

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
