### ISSUE TITLE
Use Dell Api V4

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/manufacturersimports#5]
Dell will update his web services system to v4

Must update dell.class.php

**Comment by fggroupemarck** [comment]
Bonjour tsmr,
J'aurai voulu savoir si il est possible de faire fonction le plugin 1.8.0 avec le systeme de dell V4 ou si il faut attendre la 1.8.1

Merci pour votre travail sur les plugin de GLPI

Cordialement,

**Comment by sebelec** [comment]
hi, 

do you have modified dell.class.php for API V4 from dell ?

Thanks for your work !

**Comment by jhenkins** [comment]
Hello,

I am very interested in trying out a modified dell.class.php in order to engage the Dell v.4 API. The old v.2 API is not working very well anymore. Is there any update on this, please?

Thanks for the work!

Regards,
Jan Henkins

**Comment by tomolimo** [comment]
Should be fixed with #22
