### ISSUE TITLE
HP warrantly does not work

### ISSUE THREAD

**Issue by imode92** [InfotelGLPI/manufacturersimports#50]
Hello

GLPI version : GLPI 9.2.1
Plugin version : 2.0.0

When i try to take the details of warrantly he does work...

He say " Problem when importing"

For the settings i use this URL : http://h20565.www2.hpe.com/hpsc/wc/public/find

when I click Manufacturer Information
he sends me back to the hp website where I can see the serial number but he asks for the Product number

Someone can help me please ...

**Comment by lcedro** [comment]
i have the same problem! need help!
![1](https://user-images.githubusercontent.com/38327140/39000411-5dbde98a-43ca-11e8-86f2-354a70d637b5.png)
![2](https://user-images.githubusercontent.com/38327140/39000412-5de6a5f0-43ca-11e8-820a-1ba4289a0838.png)
