### ISSUE TITLE
Dell API Key, too long

### ISSUE THREAD

**Issue by psychomoise** [InfotelGLPI/manufacturersimports#52]
* Version of the plugin : 2.0.0
* Version of your GLPI : 9.2.1
* Steps to reproduce (which actions have you made) : 
create a new supplier import for Dell, save it with Dell API key provided by Dell.

* Expected result : the key provided should be complete

* Actual result : the key is truncated to 32chars as the field in the database that is called supplier_key is a varchar(32)

* URL of the page : glpi/plugins/manufacturersimports/front/config.form.php?id=2

* Solution : next update of the plugin should contain this to correct the issue and administror will have to  provide agin their dell API key if it was longer than 32 characters : ALTER TABLE `glpi_plugin_manufacturersimports_configs` CHANGE `supplier_key` `supplier_key` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;

**Comment by raufis27** [comment]
Thank you!

**Comment by amma35** [comment]
Duplicate https://github.com/InfotelGLPI/manufacturersimports/commit/6957f4b3546da0c5b1d197c5378206269b592d69
