### ISSUE TITLE
Toshiba: extended warranty will not be considered

### ISSUE THREAD

**Issue by joschi99** [InfotelGLPI/manufacturersimports#58]
Hello,

* Version of the plugin : 2.0.0
* Version of your GLPI : 9.2.3
* Steps to reproduce (which actions have you made) :
importing warranty status of Toshiba devices is working, but the plugin is considering only standard warranty and not extended warranty.

![image](https://user-images.githubusercontent.com/6400595/42682652-81e57c0c-868b-11e8-8db6-afeeeef4d7bd.png)
![image](https://user-images.githubusercontent.com/6400595/42682701-9a6c7b54-868b-11e8-85ff-c5cf47298a3e.png)

It would be great to check also extended warranty if exists.

Regards,
Jochen

**Comment by amma35** [comment]
Hi,

I don't have a PC with an extended warranty on hand.

Can you try this modification: 
File inc/toshiba.class.php, at the end of the file the function getExpirationDate from line 91 to 98.

You replace with this part of code : 
```
   function getExpirationDate($contents) {
      $field     = "Expiration Date";
      $pos       = strripos($contents, $field);
      $searchfin = substr($contents, $pos);
      $myEndDate = substr($searchfin, 143, 10);
      $myEndDate = trim($myEndDate);
      $myEndDate = PluginManufacturersimportsPostImport::checkDate($myEndDate);
      return $myEndDate;
   }
```

**Comment by joschi99** [comment]
Hi @amma35,
I tried to update the class, but the result seem's not change. But attached you can find a complete html output for a Toshiba device using extended support:
[unitdetails.zip](https://github.com/InfotelGLPI/manufacturersimports/files/2192949/unitdetails.zip)

Let me know how I can help you.

**Comment by amma35** [comment]
Ok thanks for the example and your help.

I made some modifications, it works with your example, I get this well: 
![warranty](https://user-images.githubusercontent.com/15138371/42696107-87b489bc-86b7-11e8-8091-1a28268a44f3.png)

I make the changes for the next version of the plugin, but for version 2.0.0 you can replace this file in inc/ : 
[toshiba.class.php.zip](https://github.com/InfotelGLPI/manufacturersimports/files/2192993/toshiba.class.php.zip)

**Comment by joschi99** [comment]
Great, seem's working. Many thanks. If you need help on issue #59 please let me know.
