### ISSUE TITLE
Lenovo: extended warranty will not be considered

### ISSUE THREAD

**Issue by joschi99** [InfotelGLPI/manufacturersimports#59]
Hello,

* Version of the plugin : 2.0.0
* Version of your GLPI : 9.2.3
* Steps to reproduce (which actions have you made) :
importing warranty status of Toshiba devices is working, but the plugin is considering only standard warranty and not extended warranty.

It would be great to check also extended warranty if exists.

Regards,
Jochen

**Comment by amma35** [comment]
Are you talking about Lenovo? 
you changed the url in the configuration with "https://www.lenovo.com/us/en/warrantyApos?serialNumber=" to make it work? 

Same problem as the other issue, I don't have a PC with extended warranty.

**Comment by Wolvverine** [comment]
link:
https://www.lenovo.com/us/en/warranty/{serialnumber}?machineType={???}&btnSubmit
but ansver is in json file.

**Comment by WooboyTW** [comment]
I have sent a  PR to resolve this bug.
https://github.com/InfotelGLPI/manufacturersimports/pull/62
