### ISSUE TITLE
Préconfiguration HP n'apapraît pas dans la liste

### ISSUE THREAD

**Issue by CHCI74** [InfotelGLPI/manufacturersimports#6]
le problème se pose avec GLPI 0.85.4 et 0.90
Dernière version du plugin iinstallée 1.8.0
La préconfiguration pour le matériel HP n'apparaît pas dans la liste.
Voir pièce jointe
![pb import fabricant](https://cloud.githubusercontent.com/assets/12545704/10691806/70a20686-798c-11e5-94f8-70daa6580f42.jpg)

**Comment by tsmr** [comment]
HP a changé de langage au niveau de son site web, et nous sommes toujours en recherche d'une méthode pas trop contraignante pour récupérer les informations. Une fois celle-ci trouvée et développée, nous réactiveront la possibilité de récupérer les garanties HP
