### ISSUE TITLE
Class 'PluginManufacturersimports' not found

### ISSUE THREAD

**Issue by arkanium** [InfotelGLPI/manufacturersimports#60]
Hi,

I have an error when i launch the module
PHP Fatal error:  Class 'PluginManufacturersimports' not found in /var/www/glpi/plugins/manufacturersimports/inc/preimport.class.php on line 538, referer: http://glpi.XXXX/plugins/manufacturersimports/front/import.php

Glpi version 9.3  / Manufacturer import 2.1.0

I uninstalled the module, cleaned the files, compare my file and the one from github (they are the same). 

Thanks

**Comment by amma35** [comment]
The problem comes from your plugin setup.
What are the names of the manufacturers you have created? 
Can you put a screenshot of the http://glpi.XXXX/plugins/manufacturersimports/front/config.php page?

**Comment by arkanium** [comment]
The problem occurs every time i choose Fujitsu manufacturer.

I just created an another one (Dell without changing anything of basics parameters), if works.
I only have Fujistu computers, i can't try another manufacturer for real test.

the config page look like the scrennshot (the (1) is fujitsu preset).
![glpi](https://user-images.githubusercontent.com/11721194/42756746-d433ded0-88fd-11e8-8cba-5db431690fcc.png)

**Comment by amma35** [comment]
Your config is not good because when adding in the Fujistu config the values are not pre-filled because for the moment the imports do not work.
You must enter the name "Fujistu" or it will not work.

**Comment by arkanium** [comment]
Ok.
Tanks for the information. I hope it will work soon.
Have a nice day
