### ISSUE TITLE
Dell API key invalide

### ISSUE THREAD

**Issue by genohunter** [InfotelGLPI/manufacturersimports#7]
API key public n'est actullement plus valide : 1adecee8a60444738f280aad1cd87d0e

```xml
<Fault><Code>eAPI-40102</Code><Url>http://developer.dell.com/faults#eAPI-40102</Url><Message>Failed to Authenticate User</Message><Reason>User Identification failed in Key Management Service</Reason><Source>Gateway</Source></Fault>
```
Savez-vous si vous pouvez remplacer cette clé par une clé valide ?

Savez-vous s'il est possible d'en avoir une personnelle ? 
J'ai pas trouvé d'information claire à ce sujet.

Merci à vous

**Comment by bacus99** [comment]
you need to register to have the API key at dell

http://en.community.dell.com/dell-groups/supportapisgroup/

**Comment by genohunter** [comment]
Ok thank's

I get it !
