### ISSUE TITLE
Suppliers Imports plugin kees getting disabled

### ISSUE THREAD

**Issue by Geo-Ron** [InfotelGLPI/manufacturersimports#70]
Hello all,

First of all, thanks for this great plugin.

It is working fine, with the exception that is keeps on disabling itself.

![image](https://user-images.githubusercontent.com/23144316/49384569-902f5980-f71b-11e8-95ef-4d03fb8e0c04.png)

I have a brand new glpi 9.3.3 installation on windows.

No real problem for now, but I thought it would be nice to mention it to you all.

**Comment by keha35** [comment]
Hello,

It can be beacuse of another plugin.
Have you tried to desabled all your plugin and enable only manufacturersimports?

**Comment by Geo-Ron** [comment]
I will try this...

Met vriendelijke groet, With kind regards,

*Ron Peeters*




Op ma 3 dec. 2018 om 17:33 schreef Kevin HAINRY <notifications@github.com>:

**Comment by Geo-Ron** [comment]
I have disabled all the plugins.
Enabled the manufacturersimports and after 'some time' it gets disabled.
This can be very fast (enabling it, opening the configuration and immediately receive the error message that the plugin is disabled),
but also after several minutes (importing several hundred devices as we go untill we receive the error message that the plugin is disabled)

**Comment by Geo-Ron** [comment]
Is there any log I can dig in to on why this plugin keeps getting disabled??

**Comment by amma35** [comment]
Hi,
You should check your server configuration the plugin is disabled if it does not have access to the soap or curl or json service. These are the prerequisites that can disable the plugin.

**Comment by Geo-Ron** [comment]
![image](https://user-images.githubusercontent.com/23144316/55715756-b466b400-59f5-11e9-8c0b-2ed29fe05337.png)

These are enabled, as far as I can see.
Are there any server side logs that I can get into? I've tried but did not find any reason why it is being disabled….

**Comment by tsmr** [comment]
Old issue, i close
