### ISSUE TITLE
Dell Devices not import

### ISSUE THREAD

**Issue by MichaHN** [InfotelGLPI/manufacturersimports#71]
Hello together,

i'm new here and have start with glpi for managed my environment.

i have a new GLPI (9.3.2) installation on Debian Linux with the Plugins OCS (1.5.4) and Suppliers Imports (2.1.2).
for the Suppliers Imports i have create a Dell Api Key for warranty. The key has 37 chars. 

all work fine, but i cant import the devices. the error is "Problem during the importation"
![glpierror1](https://user-images.githubusercontent.com/45588088/49427159-e693ab00-f7a2-11e8-8754-5c32d7baed40.jpg)

the information in the Manufacture link are correct. I can see the start and end date of the warranty and which service i have.

any ideas ?

cherrs
Micha

**Comment by keha35** [comment]
Hi,

Do you have log errors when importing? (glpi/files/_log/php-errors.log and sql-errors.log)

**Comment by MichaHN** [comment]
no :-(

**Comment by keha35** [comment]
I've test with your configuration and it worked 
![image](https://user-images.githubusercontent.com/39367117/49446132-bc0e1600-f7d3-11e8-869d-5b35c60898a3.png)

Did you have a proxy ?
If yes, you need to configure it in "Setup > General > System > Proxy configuration for upgrade check".

**Comment by MichaHN** [comment]
you my hero - it works.

many thanks
