### ISSUE TITLE
Dell digital delivery bug

### ISSUE THREAD

**Issue by boscorelly** [InfotelGLPI/manufacturersimports#72]
#8 

hi,

the problem occured before, and it seems that it mai re-happen again

https://api.dell.com/support/assetinfo/v4/getassetwarranty/G3XBPC2?apikey=cdfb05f4-9143-41c1-b871-ce8f6eb0ca9a

plugin has used the digital delivery date for warranty

**Comment by boscorelly** [comment]
and of course i am up to date

**Comment by amma35** [comment]
With your example, it is not the "Dell Digitial Delivery" guarantee that is taken but this one:  

```
[StartDate] => 2016-09-21T19:00:00
[EndDate] => 2019-09-22T18:59:59
[ServiceLevelDescription] => ProSupport with Next Business Day Service
[ServiceLevelCode] => NU
[ServiceLevelGroup] => 5
[EntitlementType] => INITIAL
[ServiceProvider] => 
[ItemNumber] => 710-46622
```

**Comment by boscorelly** [comment]
The xml result has changed... no more problem 🙄
