### ISSUE TITLE
HPE Manufacturer

### ISSUE THREAD

**Issue by dreamsness** [InfotelGLPI/manufacturersimports#74]
Hello,

First of all, I would like to thank you for all the work you are doing.
I have a request regarding HPE manufacturer.

Version of the plugin :
2.1.2

Version of your GLPI :
GLPI 9.3.0

The new version of the plugin uses the URL https://css.api.hp.com/oauth/v1/token with the use of API key.
It allows to obtain HP guarantees but does not allow to have HPE guarantees. In their emails, HP points out that HP is different from HPE.

The old version worked for HPE without API key using the URL: http://h20565.www2.hpe.com/hpsc/wc/public/find
How to reuse the old method for HPE guarantees ?
Is it possible to create a preconfiguration for HPE ?

Thank you again for everything you do.

Best regards,
José

**Comment by Megachip** [comment]
@keha35 seems not working (anymore) 
https://support.hpe.com/connect/s/warrantycheck is the Manufacturer web address.
Not sure what the actual api URLs are.

Maybe preconfiguration should also differ between HP and HPE
