### ISSUE TITLE
Update plugin for glpi 9.4

### ISSUE THREAD

**Issue by DavidSerre** [InfotelGLPI/manufacturersimports#75]
* Version of your GLPI : 9.4.0

Hi, 

Have you planned to update your plugin for version 9.4 of glpi ?

**Comment by rupter** [comment]
Hi,
I updated GLPI to 9.4.
I wanted to update your plugin that is 2.1.2 and 9.4 compatible in the comments but it does not work.
Indication that it is compatible only in 9.3.

**Comment by rupter** [comment]
Hi,
Little up =D

**Comment by akurach** [comment]
you can install it in 9.4+ via git. 
just do 

```
git clone https://github.com/InfotelGLPI/manufacturersimports
```

in plugin dir. 

don't forget to install php soap module

**Comment by DavidSerre** [comment]
Thanks a lot, it's work !

**Comment by dani** [comment]
While the GIT version works with GLPI 9.4, it'd be great to make a new release. In my case, I deploy everything using ansible, and using the GIT version is not really possible (I'd need to develop another way to handle plugins, just for manufacturersimports). I'm sure I'm not the only one in this case :-)

**Comment by akurach** [comment]
> While the GIT version works with GLPI 9.4, it'd be great to make a new release. In my case, I deploy everything using ansible, and using the GIT version is not really possible (I'd need to develop another way to handle plugins, just for manufacturersimports). I'm sure I'm not the only one in this case :-)

u could use ansible git module. it's simple

**Comment by dani** [comment]
I could of course. But that'd be a pain to manage (either I never update, or I always run latest snapshot, which might break). For all the other modules I just declare the plugin name, and its version, and my role will fetch the corresponding tarball, install it cleanly, and handle updates when needed. Versionned tarball are easier to manage. And the plugin could be marked compatble with 9.4 on plugins.glpi-project.org (which is not the case now)
