### ISSUE TITLE
Support for GLPI 9.4.2?

### ISSUE THREAD

**Issue by GitStorm** [InfotelGLPI/manufacturersimports#76]
I am planning to upgrade GLPI from 9.3+1.2 to 9.4.2.
Is version 2.1.2 of your plugin supported with GLPI 9.4.2?

**Comment by Alwaysin** [comment]
No, you have to retrieve the plugin from git, not from the releases page.

See https://github.com/InfotelGLPI/manufacturersimports/issues/75#issuecomment-482511843

**Comment by GitStorm** [comment]
Allright, will do - thanks!

**Comment by keha35** [comment]
Hi,

The release has been uploaded.

BR.
