### ISSUE TITLE
Import HP ne fonctionne plus...

### ISSUE THREAD

**Issue by Langelot007** [InfotelGLPI/manufacturersimports#77]
------------
* Version of the plugin : 2.1.2
* Version of your GLPI : 9.3.0
* Steps to reproduce (which actions have you made) :

Outils/import fabricant/select =>ordinateur =>root>HP  => matériel non-importé => envoyer

Coché 1 PC non importé => import => envoyer

* Expected result :
Importation des dates de garantie

* Actual result :
Import KO
debug mode activé : 
PHP Warning: reset() expects parameter 1 to be array, null given in D:\xampp\htdocs\hotline\plugins\manufacturersimports\inc\hp.class.php at line 78
PHP Warning: reset() expects parameter 1 to be array, null given in D:\xampp\htdocs\hotline\plugins\manufacturersimports\inc\hp.class.php at line 78
PHP Warning: reset() expects parameter 1 to be array, null given in D:\xampp\htdocs\hotline\plugins\manufacturersimports\inc\hp.class.php at line 98
PHP Warning: reset() expects parameter 1 to be array, null given in D:\xampp\htdocs\hotline\plugins\manufacturersimports\inc\hp.class.php at line 110
PHP Warning: reset() expects parameter 1 to be array, null given in D:\xampp\htdocs\hotline\plugins\manufacturersimports\inc\hp.class.php at line 110

Pour ces lignes :       $contents = reset($contents);

* URL of the page :
http://serv/hotline/plugins/manufacturersimports/ajax/massiveaction.php

Cela a parfaitement fonctionner pendant quelques mois et depuis avril-mai je n'est pas fais attention et personne ne m'as remonter le soucis avant aujourd'hui...  

Ma clé API est bonne.

le plugin fonctionne parfaitement avec DELL et LENOVO

**Comment by Bounzz** [comment]
J'ai exactement le même problème.

**Comment by mbirkler** [comment]
J'ai exactement le même problème.

**Comment by pierre-guillot** [comment]
Bonjour,

Ce problème semble provenir de HP directement si on regarde sur leur forum : https://developers.hp.com/hp-client-management/forum/warranty-api-currently-unavailable
Il faut malheureusement attendre qu'ils corrigent le problème...

**Comment by bbreton09** [comment]
Bonjour, 
HP ne semblant pas vouloir relancer son API il semble que certain utilise une méthode alternative : https://www.cyberdrain.com/automating-with-powershell-automating-warranty-information-reporting/
Pensez vous que cette technique soit transposable dans le plugin ?

**Comment by pablitobin** [comment]
> Bonjour, HP ne semblant pas vouloir relancer son API il semble que certain utilise une méthode alternative : https://www.cyberdrain.com/automating-with-powershell-automating-warranty-information-reporting/ Pensez vous que cette technique soit transposable dans le plugin ?
> 
> La fonction est ici : https://github.com/KelvinTegelaar/PowerShellWarrantyReports/blob/master/private/Get-HPWarranty.ps1

Any news about this?

**Comment by tsmr** [comment]
Old issue, i close
