### ISSUE TITLE
Dell API - V5

### ISSUE THREAD

**Issue by pablitobin** [InfotelGLPI/manufacturersimports#79]
Hi!
Dell changes their API procedures to get warranty status. They are using V5 now.
Somebody knows how to fix it?

**Comment by thunderdome2** [comment]
Hello.

Here is the documentation about the new API: http://techdirect.dell.com/API_DOCs/Dell%20Warranty%20API%20Version%205.zip
The current API (v4) will be shutdown at the end of the year: https://techdirect.dell.com/portal/InfoCenter.aspx#TechDirectAPIs

**Comment by LDanton95** [comment]
Hello,
I request a new API (V5) from Dell and read the documentation.
Unfortunately, I don't understand how to setup the new key for GLPI plugin.

Could someone can help me (us) to implement the new API on GLPI (9.3 for me).

Thanks a lot in advance.
Ludo.

**Comment by abpetit** [comment]
Hello, 
The same for me, can someone help us please ?
Thanks,
Alex.

**Comment by LDanton95** [comment]
Hello,
I'm sure our issue could concerne many people who will need to change to the new Dell API.
I'll very appreciate if someone could help us.

Thanks in advance,
Ludo.

**Comment by keha35** [comment]
Hi, 

The developpement for the api V5 is in progress.

Br.

**Comment by LDanton95** [comment]
Hi,
Ok Thanks !
Waiting for good news ;-)

Regards,
Ludo.

**Comment by thunderdome2** [comment]
Hello.

Can you attaach the commit? So we can test it.

Regards.

**Comment by boscorelly** [comment]
> Hi,
> 
> The developpement for the api V5 is in progress.
> 
> Br.

Is it available in devel version ?

**Comment by Supergupin** [comment]
> 
> 
> Hi,
> 
> The developpement for the api V5 is in progress.
> 
> Br.

Hi, 
any news about the developpement of the API v5?
Do you have some issue about it?

Thank you.

Cheers

**Comment by hesleymagno** [comment]
**For ERROR** 



This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Fault xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://api.dell.com/faults">

<Code>eAPI-401</Code>

<Url>http://developer.dell.com/faults#eAPI-50020</Url>

<Message>Invalid API Key</Message>

<ErrorSubCode>0x00d30003</ErrorSubCode>

<ResourceURI>

https://sandbox.apidp.dell.com/support/assetinfo/v5/getassetwarranty/95F1QK2?apikey=eaf1xxxxxxxxxxxxxxxxxxxxxxxxd55a7

</ResourceURI>

</Fault>



**DELL API SUPPORT**

Please note there is no Sandbox/Test endpoints applicable to Warranty V5 API. You can use same Access token URI and Warranty endpoints across test and production instances.

Kindly note Warranty V5 can’t be accessed directly through web browser as the step 1 is a HTTP POST Method.

 

As we have upgraded to OAuthTLS2.0 as the authorization process hence it will be two-step process now to access new endpoint(s):

1.                Generate Bearer token using client_id and client_secret

HTTP POST Method ; URI : https://apigtwb2c.us.dell.com/auth/oauth/v2/token

requestBody

   grant_type    = client_credentials

   client_id     = your client_id

   client_secret = your client_secret

   Content-Type = application/x-www-form-urlencoded


![image](https://user-images.githubusercontent.com/34041044/70909742-df75be80-1fec-11ea-9e64-0668eac8fad8.png)

 

2.                Use the Bearer token to make Warranty API call (new endpoints for warranty V5 API) wherein Bearer token should be passed as Header whilst servicetag (s) as query parameter - refer Warranty technical specs for more details

HTTP GET Method -  Below are the various URI

GetAssetHeader:                https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/assets?

GetAssetWarranty:            https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?

GetAssetSummary:            https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlement-components?

GetAssetDetail:                  https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-components?

Headers

Authorization = Bearer $token

body = @{

                              servicetags = $tag

 
![image](https://user-images.githubusercontent.com/34041044/70909779-eef50780-1fec-11ea-8fc4-df6bafa46ef2.png)

**Comment by vinz38500** [comment]
Hello, 
Any Up ?
I have my Client_ID & my Client_Secret and the v4 stopped working on DELL site this Sunday Dec. 15th :(
This becomes, I guess for a lot of people, an urgent problem ;)
thanks in advance
Vincent

**Comment by Phaide** [comment]
Hi,
Up !
Thanks

**Comment by pablitobin** [comment]
Somebody knows when will be a DEV version to test?

**Comment by bigben386** [comment]
Just curious if there is any broad ETA on this. I am hoping to avoid a several thousand dollar Warranty Master agreement.
Thanks

**Comment by tomolimo** [comment]
Hello,
I'm working on this issue, so WIP :smiley: 
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Currently fixed for GLPI 9.2 see #80 
Next week if I've time, I'll merge the fix for 9.3 and 9.4
Regards,
Tomolimo

**Comment by Langelot007** [comment]
Merci Tomolimo ! 
Nous espérons que tu auras le temps !

**Comment by tomolimo** [comment]
Hello,
Currently fixed for GLPI 9.3 see #81 
GLPI 9.4 is coming 😃 ...
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello
PR #81 is for GLPI 9.4
Thank you
Regards,
Tomolimo

**Comment by boscorelly** [comment]
what to use for Access token API address and Warranty API address ?

**Comment by tomolimo** [comment]
Hello,
Here are the default values that appear when default DELL template is requested:

Manufacturer web address: https://www.dell.com/support/home/product-support/servicetag/
Access token API address: https://apigtwb2c.us.dell.com/auth/oauth/v2/token
Warranty API address: https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=

Regards,
Tomolimo

**Comment by Torpyl** [comment]
Hi tomolino, 

thanks for your job ! We have an issue, we d'ont have "submit" button to register the dell manufacturer configuration, any fix for this ?

thanks in advance

**Comment by tomolimo** [comment]
> Hi tomolino,
> 
> thanks for your job ! We have an issue, we d'ont have "submit" button to register the dell manufacturer configuration, any fix for this ?
> 
> thanks in advance

Please open a new issue
