### ISSUE TITLE
Submit button 

### ISSUE THREAD

**Issue by tht1991** [InfotelGLPI/manufacturersimports#84]
hello please excuse me for my english
I open this ticket for a problem during the configuration of the manufacturers. I cannot validate the preconfiguration because the "Validate" button has disappeared.

I add you a screenshot

![capture](https://user-images.githubusercontent.com/60428460/73351171-b5234c00-428e-11ea-8c21-8db792007dd9.PNG)

Here is my configuration:
- Windows Server 2016 Standard
- MySQL 8.0
- PHP 7.2
- IIS
- GLPI 9.4.3

Thank you for your answers

**Comment by Torpyl** [comment]
same issue here.

If you have any solution, thanks in advance !!

**Comment by servain-m** [comment]
Have a look to your GLPI active profile. Verify if the update and create rights are allowed for the Manufacturer Import Plugin. Or change your profile for Super-Admin if you can.

**Comment by Torpyl** [comment]
Hi Mathieu,

Thanks for your reply.

I’m already with Super-Admin Profil.

We have the last version of GLPI and the plugins.

Can you tell me how ican create specific right for the mAnufacteur Import Plugins ?

Regards

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Mathieu Servain<mailto:notifications@github.com>
Envoyé le :vendredi 14 février 2020 16:40
À : InfotelGLPI/manufacturersimports<mailto:manufacturersimports@noreply.github.com>
Cc : Torpyl<mailto:torpyl@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [InfotelGLPI/manufacturersimports] Submit button (#84)


Have a look to your GLPI active profile. Verify if the update and create rights are allowed for the Manufacturer Import Plugin. Or change your profile for Super-Admin if you can.

**Comment by tht1991** [comment]
Hello, thank you for your answer.
I am in a "Super Admin" profile and the rights for this profile on the plugin are active. Despite this, the button does not appear
![capture](https://user-images.githubusercontent.com/60428460/74545696-a05edd80-4f49-11ea-9083-c5f331ca6460.PNG)

**Comment by Torpyl** [comment]
Thans for your reply, i have the same right

 [cid:5b296a6a-34da-4603-bff9-0e8e4113d977]



Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : tht1991 <notifications@github.com>
Envoyé : Friday, February 14, 2020 4:47:11 PM
À : InfotelGLPI/manufacturersimports <manufacturersimports@noreply.github.com>
Cc : Torpyl <torpyl@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [InfotelGLPI/manufacturersimports] Submit button (#84)


Hello, thank you for your answer.
I am in a "Super Admin" profile and the rights for this profile on the plugin are active. Despite this, the button does not appear
[capture]<https://user-images.githubusercontent.com/60428460/74545696-a05edd80-4f49-11ea-9083-c5f331ca6460.PNG>

**Comment by Torpyl** [comment]
Thans for your reply, i’m already in super-admin profil too

[cid:image001.png@01D5E359.E8263430]

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : tht1991 <notifications@github.com>
Envoyé : Friday, February 14, 2020 4:47:11 PM
À : InfotelGLPI/manufacturersimports <manufacturersimports@noreply.github.com>
Cc : Torpyl <torpyl@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [InfotelGLPI/manufacturersimports] Submit button (#84)


Hello, thank you for your answer.
I am in a "Super Admin" profile and the rights for this profile on the plugin are active. Despite this, the button does not appear
[capture]<https://user-images.githubusercontent.com/60428460/74545696-a05edd80-4f49-11ea-9083-c5f331ca6460.PNG>

**Comment by Torpyl** [comment]
for more precision, it's not specific to Dell Manufacturer, but same for all

**Comment by servain-m** [comment]
Vu que tout le monde semble parler français, je continue dans cette langue où je suis plus à l'aise.

J'ai déjà été confronté à votre problème, et je l'ai résolu en donnant les bons droits sur la configuration du plugin dans GLPI. Et normalement le profil Super-Admin donne tous les droits.

Exemple de configuration du profil "Admin" : Configuration générale en "Lecture" et "Mise à jour".
![01_profil-admin-config](https://user-images.githubusercontent.com/61057899/74549259-9f30af00-4f4f-11ea-8e64-65cac5f62c16.png)

Puis Imports fabricants en lecture seule ("mise à jour", "créer" et "purger" ne sont pas cochés)
![02_profil-admin-ImportFabricants](https://user-images.githubusercontent.com/61057899/74549379-d43d0180-4f4f-11ea-9359-9554c9e5f665.png)

En activant ce profil "Admin", on peut lire la configuration du plugin Import fabricants, mais pas le modifier (le bouton "Sauvegarder" n'apparaît pas)
![03_ImportFabricants-admin](https://user-images.githubusercontent.com/61057899/74549539-19f9ca00-4f50-11ea-84f7-b0859aab5ead.png)

Alors que avec le profil "Super-Admin" ce bouton apparaît (de même en cochant "Import fabricant" > "mise à jour" sur la configuration du profil "Admin").
![04_ImportFabricants-superadmin](https://user-images.githubusercontent.com/61057899/74549671-54fbfd80-4f50-11ea-82d8-d6201d535cd8.png)

Donc si ça ne fonctionne pas pour vous, je ne vois pas pourquoi ...

**Comment by Torpyl** [comment]
Je viens de regarder ma configuration, et je pense avoir les bons droits en super-admin

[cid:image002.png@01D5E35E.E6A2D640]


[cid:image004.png@01D5E35E.CF3D9C10]
[cid:image005.png@01D5E35E.E602C5B0]


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Mathieu Servain<mailto:notifications@github.com>
Envoyé le :vendredi 14 février 2020 17:39
À : InfotelGLPI/manufacturersimports<mailto:manufacturersimports@noreply.github.com>
Cc : Torpyl<mailto:torpyl@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [InfotelGLPI/manufacturersimports] Submit button (#84)


Vu que tout le monde semble parler français, je continue dans cette langue où je suis plus à l'aise.

J'ai déjà été confronté à votre problème, et je l'ai résolu en donnant les bons droits sur la configuration du plugin dans GLPI. Et normalement le profil Super-Admin donne tous les droits.

Exemple de configuration du profil "Admin" : Configuration générale en "Lecture" et "Mise à jour".
[01_profil-admin-config]<https://user-images.githubusercontent.com/61057899/74549259-9f30af00-4f4f-11ea-8e64-65cac5f62c16.png>

Puis Imports fabricants en lecture seule ("mise à jour", "créer" et "purger" ne sont pas cochés)
[02_profil-admin-ImportFabricants]<https://user-images.githubusercontent.com/61057899/74549379-d43d0180-4f4f-11ea-9359-9554c9e5f665.png>

En activant ce profil "Admin", on peut lire la configuration du plugin Import fabricants, mais pas le modifier (le bouton "Sauvegarder" n'apparaît pas)
[03_ImportFabricants-admin]<https://user-images.githubusercontent.com/61057899/74549539-19f9ca00-4f50-11ea-84f7-b0859aab5ead.png>

Alors que avec le profil "Super-Admin" ce bouton apparaît (de même en cochant "Import fabricant" > "mise à jour" sur la configuration du profil "Admin").
[04_ImportFabricants-superadmin]<https://user-images.githubusercontent.com/61057899/74549671-54fbfd80-4f50-11ea-82d8-d6201d535cd8.png>

Donc si ça ne fonctionne pas pour vous, je ne vois pas pourquoi ...

**Comment by Torpyl** [comment]
Autre chose à vérifier ?

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Chris Torpyl <torpyl@hotmail.com>
Envoyé : Friday, February 14, 2020 5:48:57 PM
À : InfotelGLPI/manufacturersimports <reply@reply.github.com>; InfotelGLPI/manufacturersimports <manufacturersimports@noreply.github.com>
Cc : Comment <comment@noreply.github.com>
Objet : RE : [InfotelGLPI/manufacturersimports] Submit button (#84)


Je viens de regarder ma configuration, et je pense avoir les bons droits en super-admin



[cid:image002.png@01D5E35E.E6A2D640]





[cid:image004.png@01D5E35E.CF3D9C10]

[cid:image005.png@01D5E35E.E602C5B0]





Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10



De : Mathieu Servain<mailto:notifications@github.com>
Envoyé le :vendredi 14 février 2020 17:39
À : InfotelGLPI/manufacturersimports<mailto:manufacturersimports@noreply.github.com>
Cc : Torpyl<mailto:torpyl@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [InfotelGLPI/manufacturersimports] Submit button (#84)



Vu que tout le monde semble parler français, je continue dans cette langue où je suis plus à l'aise.

J'ai déjà été confronté à votre problème, et je l'ai résolu en donnant les bons droits sur la configuration du plugin dans GLPI. Et normalement le profil Super-Admin donne tous les droits.

Exemple de configuration du profil "Admin" : Configuration générale en "Lecture" et "Mise à jour".
[01_profil-admin-config]<https://user-images.githubusercontent.com/61057899/74549259-9f30af00-4f4f-11ea-8e64-65cac5f62c16.png>

Puis Imports fabricants en lecture seule ("mise à jour", "créer" et "purger" ne sont pas cochés)
[02_profil-admin-ImportFabricants]<https://user-images.githubusercontent.com/61057899/74549379-d43d0180-4f4f-11ea-9359-9554c9e5f665.png>

En activant ce profil "Admin", on peut lire la configuration du plugin Import fabricants, mais pas le modifier (le bouton "Sauvegarder" n'apparaît pas)
[03_ImportFabricants-admin]<https://user-images.githubusercontent.com/61057899/74549539-19f9ca00-4f50-11ea-84f7-b0859aab5ead.png>

Alors que avec le profil "Super-Admin" ce bouton apparaît (de même en cochant "Import fabricant" > "mise à jour" sur la configuration du profil "Admin").
[04_ImportFabricants-superadmin]<https://user-images.githubusercontent.com/61057899/74549671-54fbfd80-4f50-11ea-82d8-d6201d535cd8.png>

Donc si ça ne fonctionne pas pour vous, je ne vois pas pourquoi ...

**Comment by letsridehawk65** [comment]
Also seeing the same issue.  

GLPI - 9.4.5
Plugin - 2.2.1

Verified that Suppliers imports has Read, Update, Create, Purge under Super-Admin and that I am logged in with a Super-Admin account.  When I go to setup any of the manufacturers I only see a "Back" button.

<img width="1919" alt="Screen Shot 2020-02-18 at 10 35 25 AM" src="https://user-images.githubusercontent.com/16107856/74750911-77d12f00-523a-11ea-82af-bf85ae1013ff.png">

<img width="1920" alt="Screen Shot 2020-02-18 at 10 36 51 AM" src="https://user-images.githubusercontent.com/16107856/74750998-9afbde80-523a-11ea-8f87-5ccabd9efeda.png">

**Comment by GuiGuiSoft** [comment]
Hello,
I have the same problem :/ 

User profile : **Super-Admin** (all possible checkboxes activated :p )
**GLPI : 9.5.3
Plugins** list :
```
	news                 Name: Alertes                        Version: 1.8.0      State: Enabled
	badges               Name: Badges                         Version: 2.6.0      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.12.0     State: Enabled
	behaviors            Name: Comportements                  Version: 2.4.1      State: Enabled
	datainjection        Name: Data Injection                 Version: 2.8.1      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	manufacturersimports Name: Imports fabricants             Version: 2.3.0      State: Enabled
	matomo               Name: Matomo                         Version: 1.0.0      State: Enabled
	satisfaction         Name: Plus de satisfaction           Version: 1.5.0      State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.9.9      State: Enabled
```

**Comment by GuiGuiSoft** [comment]
J'ai résolu le problème en créant les tables à la main avec les 3 requêtes CREATE dans https://github.com/InfotelGLPI/manufacturersimports/blob/master/sql/empty-2.3.0.sql

A la [ligne 7](https://github.com/InfotelGLPI/manufacturersimports/blob/50fae5891011a8c3a1b01e1915d112b6643c38a8/sql/empty-2.3.0.sql#L7), il y a 2 fois l'instruction `COLLATE`, ce qui empêche, je suppose l'exécution de tout le script de création des tables.
En ne gardant qu'un `COLLATE`, les tables ont été créés et je peux sauvegarder ma conf.
