### ISSUE TITLE
SQL table glpi_plugin_manufacturersimports_configs missing

### ISSUE THREAD

**Issue by LilianBoulard** [InfotelGLPI/manufacturersimports#85]
Hi, 

I have an issue with the plugin : it seems the SQL table "glpi_plugin_manufacturersimports_configs" was deleted somehow...
I tried uninstalling and reinstalling the plugin, but the table doesn't get created.

* Version of the plugin : **2.2.1**

* Version of your GLPI : **9.4.5**

* Steps to reproduce (which actions have you made) : **Any action requiring SQL manipulation from the plugin, like importing unimported systems for instance.**

* Result : **Blank page when submitting, and the plugin disables itself**

* Other :

sql-errors.log tail :
>[2020-01-29 10:25:49] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_plugin_manufacturersimports_configs` WHERE `glpi_plugin_manufacturersimports_configs`.`id` = '1' LIMIT 1
  Error: Table 'glpi.glpi_plugin_manufacturersimports_configs' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:298                       DBmysql->request()
  inc/commondbtm.class.php:2803                      CommonDBTM->getFromDB()
  inc/commondbtm.class.php:2136                      CommonDBTM->can()
  inc/commondbtm.class.php:2407                      CommonDBTM->canEdit()
  ...s/manufacturersimports/inc/config.class.php:430 CommonDBTM->showFormButtons()
  inc/commonglpi.class.php:475                       PluginManufacturersimportsConfig->showForm()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

Do you have any idea on how to make the plugin recreate the necessary tables ?

Thank you,
Best regards

**Comment by Torpyl** [comment]
same issue here

**Comment by tsmr** [comment]
Corrected on master
