### ISSUE TITLE
Submit BUTTON ISSUE

### ISSUE THREAD

**Issue by Torpyl** [InfotelGLPI/manufacturersimports#87]
> Hi tomolino,
> 
> thanks for your job ! We have an issue, we d'ont have "submit" button to register the dell manufacturer configuration, any fix for this ?
> 
> thanks in advance

Please open a new issue

_Originally posted by @tomolimo in https://github.com/InfotelGLPI/manufacturersimports/issues/79#issuecomment-585193031_

**Comment by Torpyl** [comment]
Version of the plugin : 2.2.1

Version of your GLPI : 9.4.5

Steps to reproduce (which actions have you made) : nothing

Expected result : Register Dell configuration
Actual result : Submit button to register DELL Configuration not appear

**Comment by Cirixe** [comment]
Bonjour,
La table manufacturer import ne figure pas dans la base de données MySQL lors de l'installation du plugin, je l'ai donc rajouté et le bouton 'sauvegarder' est apparu.
J'ai un nouveau problème, quand je cherche à importer les dates d'achats et de garanties des postes présents dans GLPI, j'obtiens un message me disant que aucun matériel n'a été trouvé.
J'ai bien renseigné l'URL du fabricant et la clé API.
![import fabricant](https://user-images.githubusercontent.com/61828082/75973609-bcfd8e00-5ed5-11ea-8bfa-71ba8f9a35f8.PNG)

J'aimerais obtenir de l'aide, je vous remercie par avance.

**Comment by tomolimo** [comment]
Hello @Cirixe 
Please post in English!
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @Torpyl 
Could you post here the php and mysql log files?
Thank you
Regards,
Tomolimo

**Comment by Cirixe** [comment]
Hello,
The manufacturer import table does not appear in the MySQL database during the installation of the plugin, so I added it and the 'save' button appeared.
I have a new problem, when I try to import the dates of purchases and guarantees of the positions present in GLPI, I get a message telling me that no material has been found.
I have correctly entered the manufacturer's URL and the API key.


In the PHP error log file I have this:
HP Notice: Trying to get property 'num_rows' of non-object in C: \ inetpub \ wwwroot \ GLPI \ inc \ dbmysql.class.php at line 285

Thanks.

**Comment by Cirixe** [comment]
We are going forward :-)
I managed to bring up only 2 positions but the import is knocking out.
![image](https://user-images.githubusercontent.com/61828082/76075621-9d319d00-5f9d-11ea-8689-60b2c89f1324.png)

**Comment by Cirixe** [comment]
Here is the PHP error message :

![image](https://user-images.githubusercontent.com/61828082/76075694-c05c4c80-5f9d-11ea-8dc2-99b2c3bdaedf.png)

**Comment by tomolimo** [comment]
Hello @Cirixe 
Could you post here the php and mysql log files?
Thank you
Regards,
Tomolimo

**Comment by Cirixe** [comment]
Tomolimo,

No error concerning SQL logs

However here are the PHP logs:

[php-errors.log](https://github.com/InfotelGLPI/manufacturersimports/files/4298511/php-errors.log)

**Comment by Cirixe** [comment]
And when I try to import the financial information of the positions in massive mode, here is what I receive:
![image](https://user-images.githubusercontent.com/61828082/76094237-91a49d00-5fc2-11ea-83bd-92e040051bf1.png)

**Comment by tomolimo** [comment]
Hello,

I believe that something went wrong during upgrade of the plugin.

Could you check that the glpi_plugin_manufacturersimports_* tables are present in your DB?
You should have three tables:
1. glpi_plugin_manufacturersimports_config:
![image](https://user-images.githubusercontent.com/7569958/76191680-33ed9c00-61e0-11ea-97f9-291d8ab89d37.png)

1. glpi_plugin_manufacturersimports_logs
![image](https://user-images.githubusercontent.com/7569958/76191723-4c5db680-61e0-11ea-976b-bac2b45c3c91.png)

1. glpi_plugin_manufacturersimports_models
![image](https://user-images.githubusercontent.com/7569958/76191779-68f9ee80-61e0-11ea-95db-4fac958d88ef.png)

I think that something went wrong during upgrade of the "glpi_plugin_manufacturersimports_configs" table.

What I propose to you is to uninstall the plugin, and to re-install and re-enable it. Beware that it will delete the plugin tables, so you may first backup them.

And you may check the log error files (php and sql) right after the re-installation. And also check the table definition see attached screen copies.

Thank you
Regards,
Tomolimo

**Comment by Cirixe** [comment]
Hello Tomolino,

Thank you for your answer.

Precisely, I had to add them by hand since they were not present in the database.

I am not an expert in mysql, I may have created the table badly.

**Comment by Cirixe** [comment]
Tomolino,
Can you send me requests from the three tables please?

**Comment by tomolimo** [comment]
Requests for what? for backup ?

**Comment by Cirixe** [comment]
I misspoke, I wanted to know if you can pass me the sql queries from the three tables of the import manufacturer plugin

**Comment by tomolimo** [comment]
Queries for creation of the tables?

**Comment by Cirixe** [comment]
For the creation and configuration of tables, to have the exact values

**Comment by tomolimo** [comment]
you just need to uninstall / re-install the plugin, it will create the tables and fill them with the default values

**Comment by Cirixe** [comment]
Already done, the problem is that the tables are not recreated, I have to hand them over every time

**Comment by tomolimo** [comment]
You may find the script to re-create them in the /plugins/manufacturersimports/sql folder.
You can use the empty-2.1.2.sql file as an SQL script. It will recreate the tables.
The default values are hard-coded in the code, so if you add a DELL config, you should get them directly.

**Comment by tomolimo** [comment]
sorry please use the empty-2.1.3.sql and not the 2.1.2 which is not existing

**Comment by Cirixe** [comment]
I also did it, the table does not create because an error message of the request appears:


Here is this message:
![image](https://user-images.githubusercontent.com/61828082/76205279-30ffa500-61fa-11ea-925f-7bf26964a5af.png)

**Comment by tomolimo** [comment]
that's may be the root cause for the upgrade that was not working well...
What's the collation of the DB and of the mySQL server?

**Comment by tomolimo** [comment]
anyway, I didn't change the collation that was already used for former versions

**Comment by tomolimo** [comment]
you may try deleting the collations that are used in the queries

**Comment by Cirixe** [comment]
Sorry, I don't understand your request

**Comment by tomolimo** [comment]
in the queries that are used to create the table, you may delete the section regarding the collation.
ex:
```
CREATE TABLE `glpi_plugin_manufacturersimports_logs` (
   `id` int(11) NOT NULL auto_increment,
   `import_status` int(11) NOT NULL default '0',
   `items_id` int(11) NOT NULL default '0' COMMENT 'RELATION to various tables, according to itemtype (id)',
   `itemtype` varchar(100) collate utf8_unicode_ci NOT NULL COMMENT 'see .class.php file',
   `documents_id` int(11) NOT NULL default '0' COMMENT 'RELATION to glpi_documents (id)',
   `date_import` DATE default NULL,
   PRIMARY KEY  (`id`),
   UNIQUE KEY `unicity` (`import_status`,`items_id`,`itemtype`),
  KEY `FK_device` (`items_id`,`itemtype`),
  KEY `item` (`itemtype`,`items_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
```

**Comment by Cirixe** [comment]
Thank you for the indication, but I still get the same error

**Comment by tomolimo** [comment]
try deleting the "DEFAULT CHARSET"

**Comment by Cirixe** [comment]
I always get the same error..

**Comment by tomolimo** [comment]
which version of mysql server are you using?

**Comment by Cirixe** [comment]
I'm using mysql server 8.0

**Comment by tomolimo** [comment]
you may also try using MyIsam engine instead of InnoDB

**Comment by Cirixe** [comment]
With the mylsam engine, it doesn't work:

![image](https://user-images.githubusercontent.com/61828082/76209317-df5b1880-6201-11ea-8e03-670844127736.png)

**Comment by tomolimo** [comment]
beware with the lower cases and upper cases, it should be written like this: MyISAM

**Comment by tomolimo** [comment]
and also please delete the collation setting for the line 
```
`itemtype` varchar(100) collate utf8_unicode_ci NOT NULL COMMENT 'see .class.php file',
```

**Comment by Cirixe** [comment]
It's good, I deleted all the classification parameters and the table was created.
Note that there was a duplicate ranking parameter in the request script

**Comment by Cirixe** [comment]
But I always come back to the same problem when importing:
![image](https://user-images.githubusercontent.com/61828082/76211012-96a55e80-6205-11ea-9c0f-552b7c48a3ed.png)

![image](https://user-images.githubusercontent.com/61828082/76210834-38787b80-6205-11ea-8516-99150bc8ce46.png)

**Comment by tomolimo** [comment]
what do you mean by a "duplicated ranking parameter"?

**Comment by Cirixe** [comment]
In the SQL file empty-2.1.3
![image](https://user-images.githubusercontent.com/61828082/76214713-98732000-620d-11ea-8bc0-ef155f18f2f5.png)

**Comment by tomolimo** [comment]
ok, thank you, it looks like a copy/paste error

**Comment by tomolimo** [comment]
it was already present in 2.0.2 release

**Comment by Cirixe** [comment]
And here is what I get in the PHP log error file :
![image](https://user-images.githubusercontent.com/61828082/76218319-5699a800-6214-11ea-8597-7089b0605709.png)

**Comment by Cirixe** [comment]
About the error message during the import, is there something to do at the proxy ?

![image](https://user-images.githubusercontent.com/61828082/76219145-a75dd080-6215-11ea-9d63-73f8ae46d2ad.png)

**Comment by tomolimo** [comment]
Good remark, proxy must be set in GLPI menu Setup > System:
![image](https://user-images.githubusercontent.com/7569958/76222376-ce6ad100-621a-11ea-96d8-d386f0193310.png)

**Comment by Cirixe** [comment]
We don't have a proxy, do you have to disable the proxy option somewhere?

**Comment by Cirixe** [comment]
Also, only the first Dell URL works :
![image](https://user-images.githubusercontent.com/61828082/76232293-ce70ce00-6226-11ea-923c-f95ac9fab62a.png)

For the URL "https://apigtwb2c.us.dell.com/auth/oauth/v2/token" :
![image](https://user-images.githubusercontent.com/61828082/76232516-17288700-6227-11ea-8252-9c710101d4f4.png)

For the URL "https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=":
![image](https://user-images.githubusercontent.com/61828082/76232635-463ef880-6227-11ea-8f07-81448b7861dc.png)

**Comment by tomolimo** [comment]
Hello,
Could you post here a screen copy of the DELL config you have?
Like this one:
![image](https://user-images.githubusercontent.com/7569958/76288681-93fb4580-62a7-11ea-9169-8e8ed9bb1124.png)
Did you set your "client id" and "client secret"? 
Thank you,
Regards,
Tomolimo

**Comment by Cirixe** [comment]
Hello,
Yes, I configured it well with a valid API key and secret key
![image](https://user-images.githubusercontent.com/61828082/76292083-c78d9e00-62ae-11ea-8b7c-9c337817ab47.png)

**Comment by tomolimo** [comment]
A stupid question: did you get a client id and client secret for the V5 API? Or are you still using the one you get for the V4 API?

**Comment by Cirixe** [comment]
Obviously, I asked for a API v5 key on Dell

**Comment by tomolimo** [comment]
> Also, only the first Dell URL works :
> ![image](https://user-images.githubusercontent.com/61828082/76232293-ce70ce00-6226-11ea-923c-f95ac9fab62a.png)
> 
> For the URL "https://apigtwb2c.us.dell.com/auth/oauth/v2/token" :
> ![image](https://user-images.githubusercontent.com/61828082/76232516-17288700-6227-11ea-8252-9c710101d4f4.png)
> 
> For the URL "https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=":
> ![image](https://user-images.githubusercontent.com/61828082/76232635-463ef880-6227-11ea-8f07-81448b7861dc.png)

To answer this post:

The first URL is used to show a web page with the service tag. 
The second URL is used to get a token from DELL API (technically, this is an HTTP POST, not a GET)
the third URL is used to get the warranty information (json format) using the token that the second URL returns.

So if second URL can't get token, third URL can't get the warranty information.

**Comment by tomolimo** [comment]
another question: which version of the plugin and GLPI do you have?

**Comment by Cirixe** [comment]
Thank you for your information regarding URLs, should I contact Dell directly to resolve this issue?
I use GLPI 9.4.2 and manufacturers import 2.2.1.

**Comment by Cirixe** [comment]
Tomolino,

 Problem solved :)
The concern came from the URL of the field "Access token API address".
Here is the URL that worked : https://apigtwb2c.us.dell.com/auth/oauth/v2/token

**Comment by tomolimo** [comment]
What's the difference with the default URL?

**Comment by Cirixe** [comment]
The "/" at the end of the URL, but at the beginning I had indicated it well, but since at the beginning the table which was not created in the database, it could not work.

**Comment by Cirixe** [comment]
Then, you have to correct this problem of duplicates of the ranking parameter in the SQL file empty-2.1.3 :
![image](https://user-images.githubusercontent.com/61828082/76303592-450ed980-62c2-11ea-9026-688fbc82961b.png)

**Comment by tsmr** [comment]
Old issue, i close
