### ISSUE TITLE
Undefined index: fromwarranty

### ISSUE THREAD

**Issue by garydolbey** [InfotelGLPI/manufacturersimports#88]
* Version of the plugin : 2.2.1

* Version of your GLPI : 9.4.5

* Steps to reproduce (which actions have you made) :
Create a profile for importing Dell computer information
Execute the Automatic Action "DataRecoveryDELL"

* Expected result : Warranty information is imported into GLPI

* Actual result : Errors in php-errors.log
*** PHP Notice(8): Undefined index: fromwarranty
  Backtrace :
  ...nufacturersimports/inc/postimport.class.php:486 
  ...s/manufacturersimports/inc/import.class.php:109 PluginManufacturersimportsPostImport::saveImport()
  ...ins/manufacturersimports/inc/dell.class.php:183 PluginManufacturersimportsImport::importCron()
  inc/crontask.class.php:829                         PluginManufacturersimportsDell::cronDataRecoveryDELL()
  front/crontask.form.php:49                         CronTask::launch()

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by DamienLiox** [comment]
Hello Team,

I'm getting the same issue here : 

Version of the plugin : 2.2.2

Version of your GLPI : 9.4.5


log : 
*** PHP Notice(8): Undefined index: fromwarranty
Backtrace :
...nufacturersimports/inc/postimport.class.php:486
...s/manufacturersimports/inc/import.class.php:109 PluginManufacturersimportsPostImport::saveImport()
...ins/manufacturersimports/inc/dell.class.php:183 PluginManufacturersimportsImport::importCron()
inc/crontask.class.php:829 PluginManufacturersimportsDell::cronDataRecoveryDELL()
front/crontask.form.php:49 CronTask::launch()

The informations are available on the DELL website and when I query the API manually I can get them.

Any help would be great.

**Comment by enannos** [comment]
Hello everyone,

We have started using this plugin for some days now, I have the same error. 

  *** PHP Notice(8): Undefined index: fromwarranty
  Backtrace :
  ...nufacturersimports/inc/postimport.class.php:486
  ...s/manufacturersimports/inc/import.class.php:109 PluginManufacturersimportsPostImport::saveImport()
  ...ins/manufacturersimports/inc/dell.class.php:183 PluginManufacturersimportsImport::importCron()
  inc/crontask.class.php:829                         PluginManufacturersimportsDell::cronDataRecoveryDELL()
  front/crontask.form.php:49                         CronTask::launch()

GLPI: 9.4.6
Plugin version: 2.2.1

**Comment by enannos** [comment]
Hello, 

here is the information that I have received from DELL support in case it helps:

Case Management V3 API - sandbox access:
As we have upgraded to OAuth2.0, it is 2 step process to access API functions:

1.	Generate Bearer token using client_id and client_secret
HTTP POST Method ; Sandbox access token endpoint : https://apigtwb2cnp.us.dell.com/auth/oauth/v2/token

requestBody
grant_type = client_credentials
client_id = your client_id
client_secret = your client_secret
Content-Type = application/x-www-form-urlencoded

2.	Use the Bearer token to make the API call (new endpoints for case management V3 API) wherein Bearer token should be passed as Header – Please refer API technical specs for more details.
Case Management API sandbox endpoints:
WebCase: https://apigtwb2cnp.us.dell.com/Sandbox/support/case/v3/WebCase
GetCaseLite: https://apigtwb2cnp.us.dell.com/Sandbox/External/V3/Case/Update/CommonSyncCaseManagementUpdate
SearchCaseLite: https://apigtwb2cnp.us.dell.com/Sandbox/support/case/v3/searchcaselite
Method = POST
Headers:
Authorization: Bearer token
Content-Type: text/xml
Body: Enter the SOAP request xml here

**Comment by adul3** [comment]
Hi !

I'm having the same issue on GLPI 9.4.5/ManufacturersImports 2.2.1.

When I manually import machines, it works until 150 at a time, beyond the process hangs with a 502 Proxy Error...
When I launch the automatic action "DataRecoveryDELL", the process hangs after a couple of minutes and sends 502 Proxy Error :(

In the GLPI's log, i've this error (a lot of) ;
`[2020-05-29 15:38:11] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/###############/htdocs/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: fromwarranty
  Backtrace :
  ...nufacturersimports/inc/postimport.class.php:486
  ...s/manufacturersimports/inc/import.class.php:109 PluginManufacturersimportsPostImport::saveImport()
  ...ins/manufacturersimports/inc/dell.class.php:183 PluginManufacturersimportsImport::importCron()
  :                                                  PluginManufacturersimportsDell::cronDataRecoveryDELL()
  inc/crontask.class.php:829                         call_user_func()
  front/crontask.form.php:49                         CronTask::launch()
  {"user":"########@########","mem_usage":"1.229\", 10.51Mio)"}`

Thanks for any help

Regards

**Comment by adul3** [comment]
Hi !

Is there a way to execute the automatic action on command line ?
If so, can we limit the number of machines imported ?

Thanks

Regards

**Comment by adul3** [comment]
UP!

**Comment by AkhiOdys** [comment]
Hi,
Same issue on my GLPI (i have only DELL computers/servers)
API seems to be ok

**Comment by enannos** [comment]
Don't get it.
The Suppliers imports for each computer is still empty...

![grafik](https://user-images.githubusercontent.com/8511600/88647142-0c7f6900-d0c6-11ea-84b0-3f9628c7084d.png)

**Comment by enannos** [comment]
Just tested it with the last version of GLPI (9.5.1) and the latest manufacturersimports plugin.
Still the same error.

**Comment by adul3** [comment]
Hi !
Have you find a solution for this issue ?
Thanks.

**Comment by enannos** [comment]
No, still doesn't work properly with my installation.

**Comment by Arno38** [comment]
Hi,
Just fixed it this morning after months without this .. I applied some fixes fount here, here was the steps : 


1- Apply the fix of commit found in the v3 code of this plugin : https://github.com/InfotelGLPI/manufacturersimports/commit/5b2911e671e69b174f9181d7952ac766a6b9d16e#diff-c989f28a80653d90f5e596b5e1527586a22663af358f4c8f9991257edaef6a89
2- Copy your plugins/manufacturersimports/ajax/massiveaction.php into plugins/manufacturersimports/front/
3- Change the owner of the file with the right user (ex: www-user , the command is chown www-data:www-data massiveaction.php
4- Restart your webserver
5- Go into GLPI in Tools>Imports Manufacturers
6- Select the non-imported computers category , select all computers and choose the Reset Import option, then execute it
7- On the same page, recheck all computers and choose the Import option

This worked for me.
Before this I tried many things, including a clean reinstallation of the plugin (deleting all stuffs conf and files).

Tell me if this work for you ;)

**Comment by adul3** [comment]
Hi Arno38
Thanks for your advice
Which version of the plugin and of GLPI do you have ?
I'm on GLPI 9.5.5 and manufacturerimport 2.3.1 and the fix does not work :(

**Comment by tsmr** [comment]
Old issue, i close
