### ISSUE TITLE
Dell empty apikey

### ISSUE THREAD

**Issue by a-dawg** [InfotelGLPI/manufacturersimports#9]
Hi,
I'm having trouble configuring the apikey setting, even if I input it correctly when using the supplier import, I cannot see any filled information. Maybe that is because my "manufacturer information" link points to https://api.dell.com/support/v2/assetinfo/warranty/tags.json?svctags=xxxxx&apikey=
with an empty apikey parameter, how come?

**Comment by tsmr** [comment]
Configure Dell import into plugin setup

https://github.com/InfotelGLPI/manufacturersimports/issues/7
