### ISSUE TITLE
I lost my history after upgrade

### ISSUE THREAD

**Issue by castorsenior** [InfotelGLPI/manufacturersimports#94]
Hello,
I lost the history related to the configuration of the manufacturers, in the plugin, after having upgraded GLPI 9.4.5 + plugin manufacturers 2.2.0  ==> GLPI 9.5.4 + plugin manufacturers 2.3.1
My environment :
    Server : CentOS 7.9
    PHP : 7.3.27
    browser : Firefox 86.0 + Opera
Thanks for your attention !

**Comment by servain-m** [comment]
Same issue after same upgrades but from GLPI 9.5.2 + plugin manufacturers 2.2.1.

**Comment by tsmr** [comment]
Old issue, i close
