### ISSUE TITLE
Bug in report Warrantly

### ISSUE THREAD

**Issue by jgreenhalgh51** [InfotelGLPI/manufacturersimports#95]
hi we have problem with the import

Import it's ok but the date of import it's not complety correct 
In screenshot you can see warrantly imported 01/03/2022 but it's not correct 
The warrantly is 02/03/2025 , and screenshot we can see that the plugin take the first line of information.

![bug import screen 1 - glpi](https://user-images.githubusercontent.com/52402842/111064438-5893e800-84b4-11eb-8641-fcb7922e597d.png)

In the second screen we can see warrantly information is Collect and return support and not Prosupport , that the plugin take only the first line on warrantly

Can change this ?

![bug import screen 2 - glpi](https://user-images.githubusercontent.com/52402842/111064421-4154fa80-84b4-11eb-89ad-a17314318581.png)

The Plugin team.

------------
* Version of the plugin : 
* 2.3.1

* Version of your GLPI : 
9.5.2
* Steps to reproduce (which actions have you made) :

* Expected result :

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by jgreenhalgh51** [comment]
no response ?

**Comment by jgreenhalgh51** [comment]
No response with 2.3.1 - don't work

**Comment by hernani76600** [comment]
Hello,

Same problem here with some of our computers. 
GLPI 9.4
Plugin 2.2.2
Warranty extension is ok on the Dell Website. I contacted the DELL API Team but they told me the problem was the GLIP Plugin.
It's one of the most important use of GLPI in our University.

thanks for the help.

 "entitlements": [
            {
                "itemNumber": "865-72494",
                "startDate": "2020-05-21T00:00:00Z",
                "endDate": "2021-05-21T23:59:59.289Z",
                "entitlementType": "INITIAL",
                "serviceLevelCode": "FL",
                "serviceLevelDescription": "ProSupport Flex for Client",
                "serviceLevelGroup": 8
            },
            {
                "itemNumber": "709-16266",
                "startDate": "2020-05-21T00:00:00Z",
                "endDate": "2021-05-21T23:59:59.151Z",
                "entitlementType": "INITIAL",
                "serviceLevelCode": "CB",
                "serviceLevelDescription": "Collect and Return Support",
                "serviceLevelGroup": 5
            },
            {
                "itemNumber": "865-98540",
                "startDate": "2021-05-22T00:00:00.297Z",
                "endDate": "**2024-05-22T23:59:59.299Z",**
                "entitlementType": "EXTENDED",
                "serviceLevelCode": "FL",
                "serviceLevelDescription": "ProSupport Flex for Client",
                "serviceLevelGroup": 8

**Comment by tsmr** [comment]
Corrected on master

**Comment by jgreenhalgh51** [comment]
Bon
Don’t work 

Envoyé de mon iPhone

Le 30 sept. 2021 à 13:49, Xavier CAILLAUD ***@***.***> a écrit :

﻿
Closed #95.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
