### ISSUE TITLE
Error Import date of purchase and warranty Dell Computers

### ISSUE THREAD

**Issue by Maxence19** [InfotelGLPI/manufacturersimports#96]
Hello,

* Version of the plugin : 2.3.1

* Version of your GLPI : 9.5.5

* Steps to reproduce (which actions have you made) :
 I have configure plugin Manufacturer Web Import and do an API demand nearby DELL. I have receive the API DELL. 
I contacted DELL again but there is no problem on their side

* Expected result :
Raising of purchase and end of warranty dates

* Actual result :
However, I got an error message when importing computers

* URL of the page :
https://support.sopitec.com/plugins/manufacturersimports/front/config.form.php?id=1

* Screenshot of the problem (if pertinent) :
Configuration
![Sans titre](https://user-images.githubusercontent.com/78852810/124622360-5565a300-de7b-11eb-931b-68a3ae58a2e4.png)

Actual result
![ko](https://user-images.githubusercontent.com/78852810/124614091-31eb2a00-de74-11eb-8db5-1ca17174e189.jpg)

**Comment by tsmr** [comment]
Please hide your personal informations (URL, Api secret key)

**Comment by Maxence19** [comment]
C'est modifié

**Comment by Arno38** [comment]
Hi,
Just fixed it this morning after months without this .. I applied some fixes fount here, here was the steps :

1- Apply the fix of commit found in the v3 code of this plugin : 5b2911e#diff-c989f28a80653d90f5e596b5e1527586a22663af358f4c8f9991257edaef6a89
2- Copy your plugins/manufacturersimports/ajax/massiveaction.php into plugins/manufacturersimports/front/
3- Change the owner of the file with the right user (ex: www-user , the command is chown www-data:www-data massiveaction.php
4- Restart your webserver
5- Go into GLPI in Tools>Imports Manufacturers
6- Select the non-imported computers category , select all computers and choose the Reset Import option, then execute it
7- On the same page, recheck all computers and choose the Import option

This worked for me.
Before this I tried many things, including a clean reinstallation of the plugin (deleting all stuffs conf and files).

Tell me if this work for you ;)

**Comment by tsmr** [comment]
Old issue, i close
