### ISSUE TITLE
Errors with DataRecoveryDELL cron

### ISSUE THREAD

**Issue by sdescloux** [InfotelGLPI/manufacturersimports#99]
------------
* Version of the plugin : 
2.3.1
* Version of your GLPI : 
9.5.5
* Steps to reproduce (which actions have you made) : 
Launch "DataRecoveryDELL" automatic action with "Add a comment line" activated in DELL manufacturer configuration and GLPI debug mode enabled
* Expected result : 
populate all DELL computers with warranty informations and status ok in Suppliers imports page
* Actual result : 
The warranty informations is recorded but the comment and the field "warranty information" are not added and it is indicated in error when looking at the list of items not imported with "Problem during the importation" status.
If you run it manually, everything is fine. Comment and status ok.
In debug mode, I have this information in **glpi/files/_log/php-errors.log** only for the cron task.
```
[2021-08-19 10:24:06] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: fromwarranty in /var/www/glpi/plugins/manufacturersimports/inc/postimport.class.php at line 495
  Backtrace :
  ...s/manufacturersimports/inc/import.class.php:112 PluginManufacturersimportsPostImport::saveImport()
  ...ins/manufacturersimports/inc/dell.class.php:206 PluginManufacturersimportsImport::importCron()
  inc/crontask.class.php:943                         PluginManufacturersimportsDell::cronDataRecoveryDELL()
  front/crontask.form.php:49                         CronTask::launch()
```

**Comment by Arno38** [comment]
Hi,
Just fixed it this morning after months without this .. I applied some fixes fount here, here was the steps :

1- Apply the fix of commit found in the v3 code of this plugin : 5b2911e#diff-c989f28a80653d90f5e596b5e1527586a22663af358f4c8f9991257edaef6a89
2- Copy your plugins/manufacturersimports/ajax/massiveaction.php into plugins/manufacturersimports/front/
3- Change the owner of the file with the right user (ex: www-user , the command is chown www-data:www-data massiveaction.php
4- Restart your webserver
5- Go into GLPI in Tools>Imports Manufacturers
6- Select the non-imported computers category , select all computers and choose the Reset Import option, then execute it
7- On the same page, recheck all computers and choose the Import option

This worked for me.
Before this I tried many things, including a clean reinstallation of the plugin (deleting all stuffs conf and files).

Tell me if this work for you ;)

**Comment by tsmr** [comment]
Old issue, i close
